package club.bagedate.o2o.entity;

import java.util.Date;

public class HeadLine {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column headline.lineId
     *
     * @mbg.generated Tue May 14 10:43:09 CST 2019
     */
    private Integer lineid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column headline.linePriority
     *
     * @mbg.generated Tue May 14 10:43:09 CST 2019
     */
    private Integer linepriority;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column headline.lineStatus
     *
     * @mbg.generated Tue May 14 10:43:09 CST 2019
     */
    private Integer linestatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column headline.lineCreateTime
     *
     * @mbg.generated Tue May 14 10:43:09 CST 2019
     */
    private Date linecreatetime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column headline.lineUpdateTime
     *
     * @mbg.generated Tue May 14 10:43:09 CST 2019
     */
    private Date lineupdatetime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column headline.lineName
     *
     * @mbg.generated Tue May 14 10:43:09 CST 2019
     */
    private String linename;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column headline.lineLink
     *
     * @mbg.generated Tue May 14 10:43:09 CST 2019
     */
    private String linelink;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column headline.lineImg
     *
     * @mbg.generated Tue May 14 10:43:09 CST 2019
     */
    private String lineimg;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column headline.lineId
     *
     * @return the value of headline.lineId
     *
     * @mbg.generated Tue May 14 10:43:09 CST 2019
     */
    public Integer getLineid() {
        return lineid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column headline.lineId
     *
     * @param lineid the value for headline.lineId
     *
     * @mbg.generated Tue May 14 10:43:09 CST 2019
     */
    public void setLineid(Integer lineid) {
        this.lineid = lineid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column headline.linePriority
     *
     * @return the value of headline.linePriority
     *
     * @mbg.generated Tue May 14 10:43:09 CST 2019
     */
    public Integer getLinepriority() {
        return linepriority;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column headline.linePriority
     *
     * @param linepriority the value for headline.linePriority
     *
     * @mbg.generated Tue May 14 10:43:09 CST 2019
     */
    public void setLinepriority(Integer linepriority) {
        this.linepriority = linepriority;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column headline.lineStatus
     *
     * @return the value of headline.lineStatus
     *
     * @mbg.generated Tue May 14 10:43:09 CST 2019
     */
    public Integer getLinestatus() {
        return linestatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column headline.lineStatus
     *
     * @param linestatus the value for headline.lineStatus
     *
     * @mbg.generated Tue May 14 10:43:09 CST 2019
     */
    public void setLinestatus(Integer linestatus) {
        this.linestatus = linestatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column headline.lineCreateTime
     *
     * @return the value of headline.lineCreateTime
     *
     * @mbg.generated Tue May 14 10:43:09 CST 2019
     */
    public Date getLinecreatetime() {
        return linecreatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column headline.lineCreateTime
     *
     * @param linecreatetime the value for headline.lineCreateTime
     *
     * @mbg.generated Tue May 14 10:43:09 CST 2019
     */
    public void setLinecreatetime(Date linecreatetime) {
        this.linecreatetime = linecreatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column headline.lineUpdateTime
     *
     * @return the value of headline.lineUpdateTime
     *
     * @mbg.generated Tue May 14 10:43:09 CST 2019
     */
    public Date getLineupdatetime() {
        return lineupdatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column headline.lineUpdateTime
     *
     * @param lineupdatetime the value for headline.lineUpdateTime
     *
     * @mbg.generated Tue May 14 10:43:09 CST 2019
     */
    public void setLineupdatetime(Date lineupdatetime) {
        this.lineupdatetime = lineupdatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column headline.lineName
     *
     * @return the value of headline.lineName
     *
     * @mbg.generated Tue May 14 10:43:09 CST 2019
     */
    public String getLinename() {
        return linename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column headline.lineName
     *
     * @param linename the value for headline.lineName
     *
     * @mbg.generated Tue May 14 10:43:09 CST 2019
     */
    public void setLinename(String linename) {
        this.linename = linename == null ? null : linename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column headline.lineLink
     *
     * @return the value of headline.lineLink
     *
     * @mbg.generated Tue May 14 10:43:09 CST 2019
     */
    public String getLinelink() {
        return linelink;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column headline.lineLink
     *
     * @param linelink the value for headline.lineLink
     *
     * @mbg.generated Tue May 14 10:43:09 CST 2019
     */
    public void setLinelink(String linelink) {
        this.linelink = linelink == null ? null : linelink.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column headline.lineImg
     *
     * @return the value of headline.lineImg
     *
     * @mbg.generated Tue May 14 10:43:09 CST 2019
     */
    public String getLineimg() {
        return lineimg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column headline.lineImg
     *
     * @param lineimg the value for headline.lineImg
     *
     * @mbg.generated Tue May 14 10:43:09 CST 2019
     */
    public void setLineimg(String lineimg) {
        this.lineimg = lineimg == null ? null : lineimg.trim();
    }
}