package club.bagedate.o2o.entity;

import java.util.Date;

public class LocalAuth {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column localauth.localId
     *
     * @mbg.generated Tue May 14 10:43:09 CST 2019
     */
    private Integer localid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column localauth.userId
     *
     * @mbg.generated Tue May 14 10:43:09 CST 2019
     */
    private Integer userid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column localauth.localUserName
     *
     * @mbg.generated Tue May 14 10:43:09 CST 2019
     */
    private String localusername;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column localauth.localPassword
     *
     * @mbg.generated Tue May 14 10:43:09 CST 2019
     */
    private String localpassword;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column localauth.localIdCreateTime
     *
     * @mbg.generated Tue May 14 10:43:09 CST 2019
     */
    private Date localidcreatetime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column localauth.localIdUpdateTime
     *
     * @mbg.generated Tue May 14 10:43:09 CST 2019
     */
    private Date localidupdatetime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column localauth.localId
     *
     * @return the value of localauth.localId
     *
     * @mbg.generated Tue May 14 10:43:09 CST 2019
     */
    public Integer getLocalid() {
        return localid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column localauth.localId
     *
     * @param localid the value for localauth.localId
     *
     * @mbg.generated Tue May 14 10:43:09 CST 2019
     */
    public void setLocalid(Integer localid) {
        this.localid = localid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column localauth.userId
     *
     * @return the value of localauth.userId
     *
     * @mbg.generated Tue May 14 10:43:09 CST 2019
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column localauth.userId
     *
     * @param userid the value for localauth.userId
     *
     * @mbg.generated Tue May 14 10:43:09 CST 2019
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column localauth.localUserName
     *
     * @return the value of localauth.localUserName
     *
     * @mbg.generated Tue May 14 10:43:09 CST 2019
     */
    public String getLocalusername() {
        return localusername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column localauth.localUserName
     *
     * @param localusername the value for localauth.localUserName
     *
     * @mbg.generated Tue May 14 10:43:09 CST 2019
     */
    public void setLocalusername(String localusername) {
        this.localusername = localusername == null ? null : localusername.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column localauth.localPassword
     *
     * @return the value of localauth.localPassword
     *
     * @mbg.generated Tue May 14 10:43:09 CST 2019
     */
    public String getLocalpassword() {
        return localpassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column localauth.localPassword
     *
     * @param localpassword the value for localauth.localPassword
     *
     * @mbg.generated Tue May 14 10:43:09 CST 2019
     */
    public void setLocalpassword(String localpassword) {
        this.localpassword = localpassword == null ? null : localpassword.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column localauth.localIdCreateTime
     *
     * @return the value of localauth.localIdCreateTime
     *
     * @mbg.generated Tue May 14 10:43:09 CST 2019
     */
    public Date getLocalidcreatetime() {
        return localidcreatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column localauth.localIdCreateTime
     *
     * @param localidcreatetime the value for localauth.localIdCreateTime
     *
     * @mbg.generated Tue May 14 10:43:09 CST 2019
     */
    public void setLocalidcreatetime(Date localidcreatetime) {
        this.localidcreatetime = localidcreatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column localauth.localIdUpdateTime
     *
     * @return the value of localauth.localIdUpdateTime
     *
     * @mbg.generated Tue May 14 10:43:09 CST 2019
     */
    public Date getLocalidupdatetime() {
        return localidupdatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column localauth.localIdUpdateTime
     *
     * @param localidupdatetime the value for localauth.localIdUpdateTime
     *
     * @mbg.generated Tue May 14 10:43:09 CST 2019
     */
    public void setLocalidupdatetime(Date localidupdatetime) {
        this.localidupdatetime = localidupdatetime;
    }
}