package club.bagedate.o2o.entity;

import java.util.Date;

public class Place {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column place.placeId
     *
     * @mbg.generated Tue May 14 10:43:09 CST 2019
     */
    private Integer placeid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column place.placePriority
     *
     * @mbg.generated Tue May 14 10:43:09 CST 2019
     */
    private Integer placepriority;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column place.placeCreateTime
     *
     * @mbg.generated Tue May 14 10:43:09 CST 2019
     */
    private Date placecreatetime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column place.placeUpdateTime
     *
     * @mbg.generated Tue May 14 10:43:09 CST 2019
     */
    private Date placeupdatetime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column place.placeName
     *
     * @mbg.generated Tue May 14 10:43:09 CST 2019
     */
    private String placename;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column place.placeId
     *
     * @return the value of place.placeId
     *
     * @mbg.generated Tue May 14 10:43:09 CST 2019
     */
    public Integer getPlaceid() {
        return placeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column place.placeId
     *
     * @param placeid the value for place.placeId
     *
     * @mbg.generated Tue May 14 10:43:09 CST 2019
     */
    public void setPlaceid(Integer placeid) {
        this.placeid = placeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column place.placePriority
     *
     * @return the value of place.placePriority
     *
     * @mbg.generated Tue May 14 10:43:09 CST 2019
     */
    public Integer getPlacepriority() {
        return placepriority;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column place.placePriority
     *
     * @param placepriority the value for place.placePriority
     *
     * @mbg.generated Tue May 14 10:43:09 CST 2019
     */
    public void setPlacepriority(Integer placepriority) {
        this.placepriority = placepriority;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column place.placeCreateTime
     *
     * @return the value of place.placeCreateTime
     *
     * @mbg.generated Tue May 14 10:43:09 CST 2019
     */
    public Date getPlacecreatetime() {
        return placecreatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column place.placeCreateTime
     *
     * @param placecreatetime the value for place.placeCreateTime
     *
     * @mbg.generated Tue May 14 10:43:09 CST 2019
     */
    public void setPlacecreatetime(Date placecreatetime) {
        this.placecreatetime = placecreatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column place.placeUpdateTime
     *
     * @return the value of place.placeUpdateTime
     *
     * @mbg.generated Tue May 14 10:43:09 CST 2019
     */
    public Date getPlaceupdatetime() {
        return placeupdatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column place.placeUpdateTime
     *
     * @param placeupdatetime the value for place.placeUpdateTime
     *
     * @mbg.generated Tue May 14 10:43:09 CST 2019
     */
    public void setPlaceupdatetime(Date placeupdatetime) {
        this.placeupdatetime = placeupdatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column place.placeName
     *
     * @return the value of place.placeName
     *
     * @mbg.generated Tue May 14 10:43:09 CST 2019
     */
    public String getPlacename() {
        return placename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column place.placeName
     *
     * @param placename the value for place.placeName
     *
     * @mbg.generated Tue May 14 10:43:09 CST 2019
     */
    public void setPlacename(String placename) {
        this.placename = placename == null ? null : placename.trim();
    }
}