package club.bagedate.o2o.entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class PlaceExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table place
     *
     * @mbg.generated Tue May 14 10:43:09 CST 2019
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table place
     *
     * @mbg.generated Tue May 14 10:43:09 CST 2019
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table place
     *
     * @mbg.generated Tue May 14 10:43:09 CST 2019
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table place
     *
     * @mbg.generated Tue May 14 10:43:09 CST 2019
     */
    public PlaceExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table place
     *
     * @mbg.generated Tue May 14 10:43:09 CST 2019
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table place
     *
     * @mbg.generated Tue May 14 10:43:09 CST 2019
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table place
     *
     * @mbg.generated Tue May 14 10:43:09 CST 2019
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table place
     *
     * @mbg.generated Tue May 14 10:43:09 CST 2019
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table place
     *
     * @mbg.generated Tue May 14 10:43:09 CST 2019
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table place
     *
     * @mbg.generated Tue May 14 10:43:09 CST 2019
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table place
     *
     * @mbg.generated Tue May 14 10:43:09 CST 2019
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table place
     *
     * @mbg.generated Tue May 14 10:43:09 CST 2019
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table place
     *
     * @mbg.generated Tue May 14 10:43:09 CST 2019
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table place
     *
     * @mbg.generated Tue May 14 10:43:09 CST 2019
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table place
     *
     * @mbg.generated Tue May 14 10:43:09 CST 2019
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andPlaceidIsNull() {
            addCriterion("placeId is null");
            return (Criteria) this;
        }

        public Criteria andPlaceidIsNotNull() {
            addCriterion("placeId is not null");
            return (Criteria) this;
        }

        public Criteria andPlaceidEqualTo(Integer value) {
            addCriterion("placeId =", value, "placeid");
            return (Criteria) this;
        }

        public Criteria andPlaceidNotEqualTo(Integer value) {
            addCriterion("placeId <>", value, "placeid");
            return (Criteria) this;
        }

        public Criteria andPlaceidGreaterThan(Integer value) {
            addCriterion("placeId >", value, "placeid");
            return (Criteria) this;
        }

        public Criteria andPlaceidGreaterThanOrEqualTo(Integer value) {
            addCriterion("placeId >=", value, "placeid");
            return (Criteria) this;
        }

        public Criteria andPlaceidLessThan(Integer value) {
            addCriterion("placeId <", value, "placeid");
            return (Criteria) this;
        }

        public Criteria andPlaceidLessThanOrEqualTo(Integer value) {
            addCriterion("placeId <=", value, "placeid");
            return (Criteria) this;
        }

        public Criteria andPlaceidIn(List<Integer> values) {
            addCriterion("placeId in", values, "placeid");
            return (Criteria) this;
        }

        public Criteria andPlaceidNotIn(List<Integer> values) {
            addCriterion("placeId not in", values, "placeid");
            return (Criteria) this;
        }

        public Criteria andPlaceidBetween(Integer value1, Integer value2) {
            addCriterion("placeId between", value1, value2, "placeid");
            return (Criteria) this;
        }

        public Criteria andPlaceidNotBetween(Integer value1, Integer value2) {
            addCriterion("placeId not between", value1, value2, "placeid");
            return (Criteria) this;
        }

        public Criteria andPlacepriorityIsNull() {
            addCriterion("placePriority is null");
            return (Criteria) this;
        }

        public Criteria andPlacepriorityIsNotNull() {
            addCriterion("placePriority is not null");
            return (Criteria) this;
        }

        public Criteria andPlacepriorityEqualTo(Integer value) {
            addCriterion("placePriority =", value, "placepriority");
            return (Criteria) this;
        }

        public Criteria andPlacepriorityNotEqualTo(Integer value) {
            addCriterion("placePriority <>", value, "placepriority");
            return (Criteria) this;
        }

        public Criteria andPlacepriorityGreaterThan(Integer value) {
            addCriterion("placePriority >", value, "placepriority");
            return (Criteria) this;
        }

        public Criteria andPlacepriorityGreaterThanOrEqualTo(Integer value) {
            addCriterion("placePriority >=", value, "placepriority");
            return (Criteria) this;
        }

        public Criteria andPlacepriorityLessThan(Integer value) {
            addCriterion("placePriority <", value, "placepriority");
            return (Criteria) this;
        }

        public Criteria andPlacepriorityLessThanOrEqualTo(Integer value) {
            addCriterion("placePriority <=", value, "placepriority");
            return (Criteria) this;
        }

        public Criteria andPlacepriorityIn(List<Integer> values) {
            addCriterion("placePriority in", values, "placepriority");
            return (Criteria) this;
        }

        public Criteria andPlacepriorityNotIn(List<Integer> values) {
            addCriterion("placePriority not in", values, "placepriority");
            return (Criteria) this;
        }

        public Criteria andPlacepriorityBetween(Integer value1, Integer value2) {
            addCriterion("placePriority between", value1, value2, "placepriority");
            return (Criteria) this;
        }

        public Criteria andPlacepriorityNotBetween(Integer value1, Integer value2) {
            addCriterion("placePriority not between", value1, value2, "placepriority");
            return (Criteria) this;
        }

        public Criteria andPlacecreatetimeIsNull() {
            addCriterion("placeCreateTime is null");
            return (Criteria) this;
        }

        public Criteria andPlacecreatetimeIsNotNull() {
            addCriterion("placeCreateTime is not null");
            return (Criteria) this;
        }

        public Criteria andPlacecreatetimeEqualTo(Date value) {
            addCriterion("placeCreateTime =", value, "placecreatetime");
            return (Criteria) this;
        }

        public Criteria andPlacecreatetimeNotEqualTo(Date value) {
            addCriterion("placeCreateTime <>", value, "placecreatetime");
            return (Criteria) this;
        }

        public Criteria andPlacecreatetimeGreaterThan(Date value) {
            addCriterion("placeCreateTime >", value, "placecreatetime");
            return (Criteria) this;
        }

        public Criteria andPlacecreatetimeGreaterThanOrEqualTo(Date value) {
            addCriterion("placeCreateTime >=", value, "placecreatetime");
            return (Criteria) this;
        }

        public Criteria andPlacecreatetimeLessThan(Date value) {
            addCriterion("placeCreateTime <", value, "placecreatetime");
            return (Criteria) this;
        }

        public Criteria andPlacecreatetimeLessThanOrEqualTo(Date value) {
            addCriterion("placeCreateTime <=", value, "placecreatetime");
            return (Criteria) this;
        }

        public Criteria andPlacecreatetimeIn(List<Date> values) {
            addCriterion("placeCreateTime in", values, "placecreatetime");
            return (Criteria) this;
        }

        public Criteria andPlacecreatetimeNotIn(List<Date> values) {
            addCriterion("placeCreateTime not in", values, "placecreatetime");
            return (Criteria) this;
        }

        public Criteria andPlacecreatetimeBetween(Date value1, Date value2) {
            addCriterion("placeCreateTime between", value1, value2, "placecreatetime");
            return (Criteria) this;
        }

        public Criteria andPlacecreatetimeNotBetween(Date value1, Date value2) {
            addCriterion("placeCreateTime not between", value1, value2, "placecreatetime");
            return (Criteria) this;
        }

        public Criteria andPlaceupdatetimeIsNull() {
            addCriterion("placeUpdateTime is null");
            return (Criteria) this;
        }

        public Criteria andPlaceupdatetimeIsNotNull() {
            addCriterion("placeUpdateTime is not null");
            return (Criteria) this;
        }

        public Criteria andPlaceupdatetimeEqualTo(Date value) {
            addCriterion("placeUpdateTime =", value, "placeupdatetime");
            return (Criteria) this;
        }

        public Criteria andPlaceupdatetimeNotEqualTo(Date value) {
            addCriterion("placeUpdateTime <>", value, "placeupdatetime");
            return (Criteria) this;
        }

        public Criteria andPlaceupdatetimeGreaterThan(Date value) {
            addCriterion("placeUpdateTime >", value, "placeupdatetime");
            return (Criteria) this;
        }

        public Criteria andPlaceupdatetimeGreaterThanOrEqualTo(Date value) {
            addCriterion("placeUpdateTime >=", value, "placeupdatetime");
            return (Criteria) this;
        }

        public Criteria andPlaceupdatetimeLessThan(Date value) {
            addCriterion("placeUpdateTime <", value, "placeupdatetime");
            return (Criteria) this;
        }

        public Criteria andPlaceupdatetimeLessThanOrEqualTo(Date value) {
            addCriterion("placeUpdateTime <=", value, "placeupdatetime");
            return (Criteria) this;
        }

        public Criteria andPlaceupdatetimeIn(List<Date> values) {
            addCriterion("placeUpdateTime in", values, "placeupdatetime");
            return (Criteria) this;
        }

        public Criteria andPlaceupdatetimeNotIn(List<Date> values) {
            addCriterion("placeUpdateTime not in", values, "placeupdatetime");
            return (Criteria) this;
        }

        public Criteria andPlaceupdatetimeBetween(Date value1, Date value2) {
            addCriterion("placeUpdateTime between", value1, value2, "placeupdatetime");
            return (Criteria) this;
        }

        public Criteria andPlaceupdatetimeNotBetween(Date value1, Date value2) {
            addCriterion("placeUpdateTime not between", value1, value2, "placeupdatetime");
            return (Criteria) this;
        }

        public Criteria andPlacenameIsNull() {
            addCriterion("placeName is null");
            return (Criteria) this;
        }

        public Criteria andPlacenameIsNotNull() {
            addCriterion("placeName is not null");
            return (Criteria) this;
        }

        public Criteria andPlacenameEqualTo(String value) {
            addCriterion("placeName =", value, "placename");
            return (Criteria) this;
        }

        public Criteria andPlacenameNotEqualTo(String value) {
            addCriterion("placeName <>", value, "placename");
            return (Criteria) this;
        }

        public Criteria andPlacenameGreaterThan(String value) {
            addCriterion("placeName >", value, "placename");
            return (Criteria) this;
        }

        public Criteria andPlacenameGreaterThanOrEqualTo(String value) {
            addCriterion("placeName >=", value, "placename");
            return (Criteria) this;
        }

        public Criteria andPlacenameLessThan(String value) {
            addCriterion("placeName <", value, "placename");
            return (Criteria) this;
        }

        public Criteria andPlacenameLessThanOrEqualTo(String value) {
            addCriterion("placeName <=", value, "placename");
            return (Criteria) this;
        }

        public Criteria andPlacenameLike(String value) {
            addCriterion("placeName like", value, "placename");
            return (Criteria) this;
        }

        public Criteria andPlacenameNotLike(String value) {
            addCriterion("placeName not like", value, "placename");
            return (Criteria) this;
        }

        public Criteria andPlacenameIn(List<String> values) {
            addCriterion("placeName in", values, "placename");
            return (Criteria) this;
        }

        public Criteria andPlacenameNotIn(List<String> values) {
            addCriterion("placeName not in", values, "placename");
            return (Criteria) this;
        }

        public Criteria andPlacenameBetween(String value1, String value2) {
            addCriterion("placeName between", value1, value2, "placename");
            return (Criteria) this;
        }

        public Criteria andPlacenameNotBetween(String value1, String value2) {
            addCriterion("placeName not between", value1, value2, "placename");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table place
     *
     * @mbg.generated do_not_delete_during_merge Tue May 14 10:43:09 CST 2019
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table place
     *
     * @mbg.generated Tue May 14 10:43:09 CST 2019
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}