package club.bagedate.o2o.entity;

import java.util.Date;

public class ProductImg {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column productimg.productImgId
     *
     * @mbg.generated Tue May 14 10:43:09 CST 2019
     */
    private Integer productimgid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column productimg.productImgPlace
     *
     * @mbg.generated Tue May 14 10:43:09 CST 2019
     */
    private String productimgplace;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column productimg.productImgDesc
     *
     * @mbg.generated Tue May 14 10:43:09 CST 2019
     */
    private String productimgdesc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column productimg.productImgPriority
     *
     * @mbg.generated Tue May 14 10:43:09 CST 2019
     */
    private Integer productimgpriority;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column productimg.productImgCreateTime
     *
     * @mbg.generated Tue May 14 10:43:09 CST 2019
     */
    private Date productimgcreatetime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column productimg.productId
     *
     * @mbg.generated Tue May 14 10:43:09 CST 2019
     */
    private Integer productid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column productimg.productImgId
     *
     * @return the value of productimg.productImgId
     *
     * @mbg.generated Tue May 14 10:43:09 CST 2019
     */
    public Integer getProductimgid() {
        return productimgid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column productimg.productImgId
     *
     * @param productimgid the value for productimg.productImgId
     *
     * @mbg.generated Tue May 14 10:43:09 CST 2019
     */
    public void setProductimgid(Integer productimgid) {
        this.productimgid = productimgid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column productimg.productImgPlace
     *
     * @return the value of productimg.productImgPlace
     *
     * @mbg.generated Tue May 14 10:43:09 CST 2019
     */
    public String getProductimgplace() {
        return productimgplace;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column productimg.productImgPlace
     *
     * @param productimgplace the value for productimg.productImgPlace
     *
     * @mbg.generated Tue May 14 10:43:09 CST 2019
     */
    public void setProductimgplace(String productimgplace) {
        this.productimgplace = productimgplace == null ? null : productimgplace.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column productimg.productImgDesc
     *
     * @return the value of productimg.productImgDesc
     *
     * @mbg.generated Tue May 14 10:43:09 CST 2019
     */
    public String getProductimgdesc() {
        return productimgdesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column productimg.productImgDesc
     *
     * @param productimgdesc the value for productimg.productImgDesc
     *
     * @mbg.generated Tue May 14 10:43:09 CST 2019
     */
    public void setProductimgdesc(String productimgdesc) {
        this.productimgdesc = productimgdesc == null ? null : productimgdesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column productimg.productImgPriority
     *
     * @return the value of productimg.productImgPriority
     *
     * @mbg.generated Tue May 14 10:43:09 CST 2019
     */
    public Integer getProductimgpriority() {
        return productimgpriority;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column productimg.productImgPriority
     *
     * @param productimgpriority the value for productimg.productImgPriority
     *
     * @mbg.generated Tue May 14 10:43:09 CST 2019
     */
    public void setProductimgpriority(Integer productimgpriority) {
        this.productimgpriority = productimgpriority;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column productimg.productImgCreateTime
     *
     * @return the value of productimg.productImgCreateTime
     *
     * @mbg.generated Tue May 14 10:43:09 CST 2019
     */
    public Date getProductimgcreatetime() {
        return productimgcreatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column productimg.productImgCreateTime
     *
     * @param productimgcreatetime the value for productimg.productImgCreateTime
     *
     * @mbg.generated Tue May 14 10:43:09 CST 2019
     */
    public void setProductimgcreatetime(Date productimgcreatetime) {
        this.productimgcreatetime = productimgcreatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column productimg.productId
     *
     * @return the value of productimg.productId
     *
     * @mbg.generated Tue May 14 10:43:09 CST 2019
     */
    public Integer getProductid() {
        return productid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column productimg.productId
     *
     * @param productid the value for productimg.productId
     *
     * @mbg.generated Tue May 14 10:43:09 CST 2019
     */
    public void setProductid(Integer productid) {
        this.productid = productid;
    }
}