package club.bagedate.o2o.entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class ProductExample {
    //模糊查询根据姓名
    protected String fuzzySelectName;
    //分页查询
    protected Integer leftLimit;
    protected Integer limitSize;

    public Integer getLeftLimit() {
        return leftLimit;
    }

    public void setLeftLimit(Integer leftLimit) {
        this.leftLimit = leftLimit;
    }

    public Integer getLimitSize() {
        return limitSize;
    }

    public void setLimitSize(Integer limitSize) {
        this.limitSize = limitSize;
    }

    public String getFuzzySelectName() {
        return fuzzySelectName;
    }

    public void setFuzzySelectName(String fuzzySelectName) {
        this.fuzzySelectName = fuzzySelectName;
    }

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table product
     *
     * @mbg.generated Tue May 14 10:43:09 CST 2019
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table product
     *
     * @mbg.generated Tue May 14 10:43:09 CST 2019
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table product
     *
     * @mbg.generated Tue May 14 10:43:09 CST 2019
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbg.generated Tue May 14 10:43:09 CST 2019
     */
    public ProductExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbg.generated Tue May 14 10:43:09 CST 2019
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbg.generated Tue May 14 10:43:09 CST 2019
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbg.generated Tue May 14 10:43:09 CST 2019
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbg.generated Tue May 14 10:43:09 CST 2019
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbg.generated Tue May 14 10:43:09 CST 2019
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbg.generated Tue May 14 10:43:09 CST 2019
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbg.generated Tue May 14 10:43:09 CST 2019
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbg.generated Tue May 14 10:43:09 CST 2019
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbg.generated Tue May 14 10:43:09 CST 2019
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbg.generated Tue May 14 10:43:09 CST 2019
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table product
     *
     * @mbg.generated Tue May 14 10:43:09 CST 2019
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andProductidIsNull() {
            addCriterion("productId is null");
            return (Criteria) this;
        }

        public Criteria andProductidIsNotNull() {
            addCriterion("productId is not null");
            return (Criteria) this;
        }

        public Criteria andProductidEqualTo(Integer value) {
            addCriterion("productId =", value, "productid");
            return (Criteria) this;
        }

        public Criteria andProductidNotEqualTo(Integer value) {
            addCriterion("productId <>", value, "productid");
            return (Criteria) this;
        }

        public Criteria andProductidGreaterThan(Integer value) {
            addCriterion("productId >", value, "productid");
            return (Criteria) this;
        }

        public Criteria andProductidGreaterThanOrEqualTo(Integer value) {
            addCriterion("productId >=", value, "productid");
            return (Criteria) this;
        }

        public Criteria andProductidLessThan(Integer value) {
            addCriterion("productId <", value, "productid");
            return (Criteria) this;
        }

        public Criteria andProductidLessThanOrEqualTo(Integer value) {
            addCriterion("productId <=", value, "productid");
            return (Criteria) this;
        }

        public Criteria andProductidIn(List<Integer> values) {
            addCriterion("productId in", values, "productid");
            return (Criteria) this;
        }

        public Criteria andProductidNotIn(List<Integer> values) {
            addCriterion("productId not in", values, "productid");
            return (Criteria) this;
        }

        public Criteria andProductidBetween(Integer value1, Integer value2) {
            addCriterion("productId between", value1, value2, "productid");
            return (Criteria) this;
        }

        public Criteria andProductidNotBetween(Integer value1, Integer value2) {
            addCriterion("productId not between", value1, value2, "productid");
            return (Criteria) this;
        }

        public Criteria andProductnameIsNull() {
            addCriterion("productName is null");
            return (Criteria) this;
        }

        public Criteria andProductnameIsNotNull() {
            addCriterion("productName is not null");
            return (Criteria) this;
        }

        public Criteria andProductnameEqualTo(String value) {
            addCriterion("productName =", value, "productname");
            return (Criteria) this;
        }

        public Criteria andProductnameNotEqualTo(String value) {
            addCriterion("productName <>", value, "productname");
            return (Criteria) this;
        }

        public Criteria andProductnameGreaterThan(String value) {
            addCriterion("productName >", value, "productname");
            return (Criteria) this;
        }

        public Criteria andProductnameGreaterThanOrEqualTo(String value) {
            addCriterion("productName >=", value, "productname");
            return (Criteria) this;
        }

        public Criteria andProductnameLessThan(String value) {
            addCriterion("productName <", value, "productname");
            return (Criteria) this;
        }

        public Criteria andProductnameLessThanOrEqualTo(String value) {
            addCriterion("productName <=", value, "productname");
            return (Criteria) this;
        }

        public Criteria andProductnameLike(String value) {
            addCriterion("productName like", value, "productname");
            return (Criteria) this;
        }

        public Criteria andProductnameNotLike(String value) {
            addCriterion("productName not like", value, "productname");
            return (Criteria) this;
        }

        public Criteria andProductnameIn(List<String> values) {
            addCriterion("productName in", values, "productname");
            return (Criteria) this;
        }

        public Criteria andProductnameNotIn(List<String> values) {
            addCriterion("productName not in", values, "productname");
            return (Criteria) this;
        }

        public Criteria andProductnameBetween(String value1, String value2) {
            addCriterion("productName between", value1, value2, "productname");
            return (Criteria) this;
        }

        public Criteria andProductnameNotBetween(String value1, String value2) {
            addCriterion("productName not between", value1, value2, "productname");
            return (Criteria) this;
        }

        public Criteria andProductdescIsNull() {
            addCriterion("productDesc is null");
            return (Criteria) this;
        }

        public Criteria andProductdescIsNotNull() {
            addCriterion("productDesc is not null");
            return (Criteria) this;
        }

        public Criteria andProductdescEqualTo(String value) {
            addCriterion("productDesc =", value, "productdesc");
            return (Criteria) this;
        }

        public Criteria andProductdescNotEqualTo(String value) {
            addCriterion("productDesc <>", value, "productdesc");
            return (Criteria) this;
        }

        public Criteria andProductdescGreaterThan(String value) {
            addCriterion("productDesc >", value, "productdesc");
            return (Criteria) this;
        }

        public Criteria andProductdescGreaterThanOrEqualTo(String value) {
            addCriterion("productDesc >=", value, "productdesc");
            return (Criteria) this;
        }

        public Criteria andProductdescLessThan(String value) {
            addCriterion("productDesc <", value, "productdesc");
            return (Criteria) this;
        }

        public Criteria andProductdescLessThanOrEqualTo(String value) {
            addCriterion("productDesc <=", value, "productdesc");
            return (Criteria) this;
        }

        public Criteria andProductdescLike(String value) {
            addCriterion("productDesc like", value, "productdesc");
            return (Criteria) this;
        }

        public Criteria andProductdescNotLike(String value) {
            addCriterion("productDesc not like", value, "productdesc");
            return (Criteria) this;
        }

        public Criteria andProductdescIn(List<String> values) {
            addCriterion("productDesc in", values, "productdesc");
            return (Criteria) this;
        }

        public Criteria andProductdescNotIn(List<String> values) {
            addCriterion("productDesc not in", values, "productdesc");
            return (Criteria) this;
        }

        public Criteria andProductdescBetween(String value1, String value2) {
            addCriterion("productDesc between", value1, value2, "productdesc");
            return (Criteria) this;
        }

        public Criteria andProductdescNotBetween(String value1, String value2) {
            addCriterion("productDesc not between", value1, value2, "productdesc");
            return (Criteria) this;
        }

        public Criteria andProductplaceIsNull() {
            addCriterion("productPlace is null");
            return (Criteria) this;
        }

        public Criteria andProductplaceIsNotNull() {
            addCriterion("productPlace is not null");
            return (Criteria) this;
        }

        public Criteria andProductplaceEqualTo(String value) {
            addCriterion("productPlace =", value, "productplace");
            return (Criteria) this;
        }

        public Criteria andProductplaceNotEqualTo(String value) {
            addCriterion("productPlace <>", value, "productplace");
            return (Criteria) this;
        }

        public Criteria andProductplaceGreaterThan(String value) {
            addCriterion("productPlace >", value, "productplace");
            return (Criteria) this;
        }

        public Criteria andProductplaceGreaterThanOrEqualTo(String value) {
            addCriterion("productPlace >=", value, "productplace");
            return (Criteria) this;
        }

        public Criteria andProductplaceLessThan(String value) {
            addCriterion("productPlace <", value, "productplace");
            return (Criteria) this;
        }

        public Criteria andProductplaceLessThanOrEqualTo(String value) {
            addCriterion("productPlace <=", value, "productplace");
            return (Criteria) this;
        }

        public Criteria andProductplaceLike(String value) {
            addCriterion("productPlace like", value, "productplace");
            return (Criteria) this;
        }

        public Criteria andProductplaceNotLike(String value) {
            addCriterion("productPlace not like", value, "productplace");
            return (Criteria) this;
        }

        public Criteria andProductplaceIn(List<String> values) {
            addCriterion("productPlace in", values, "productplace");
            return (Criteria) this;
        }

        public Criteria andProductplaceNotIn(List<String> values) {
            addCriterion("productPlace not in", values, "productplace");
            return (Criteria) this;
        }

        public Criteria andProductplaceBetween(String value1, String value2) {
            addCriterion("productPlace between", value1, value2, "productplace");
            return (Criteria) this;
        }

        public Criteria andProductplaceNotBetween(String value1, String value2) {
            addCriterion("productPlace not between", value1, value2, "productplace");
            return (Criteria) this;
        }

        public Criteria andProductoldpriceIsNull() {
            addCriterion("productOldPrice is null");
            return (Criteria) this;
        }

        public Criteria andProductoldpriceIsNotNull() {
            addCriterion("productOldPrice is not null");
            return (Criteria) this;
        }

        public Criteria andProductoldpriceEqualTo(String value) {
            addCriterion("productOldPrice =", value, "productoldprice");
            return (Criteria) this;
        }

        public Criteria andProductoldpriceNotEqualTo(String value) {
            addCriterion("productOldPrice <>", value, "productoldprice");
            return (Criteria) this;
        }

        public Criteria andProductoldpriceGreaterThan(String value) {
            addCriterion("productOldPrice >", value, "productoldprice");
            return (Criteria) this;
        }

        public Criteria andProductoldpriceGreaterThanOrEqualTo(String value) {
            addCriterion("productOldPrice >=", value, "productoldprice");
            return (Criteria) this;
        }

        public Criteria andProductoldpriceLessThan(String value) {
            addCriterion("productOldPrice <", value, "productoldprice");
            return (Criteria) this;
        }

        public Criteria andProductoldpriceLessThanOrEqualTo(String value) {
            addCriterion("productOldPrice <=", value, "productoldprice");
            return (Criteria) this;
        }

        public Criteria andProductoldpriceLike(String value) {
            addCriterion("productOldPrice like", value, "productoldprice");
            return (Criteria) this;
        }

        public Criteria andProductoldpriceNotLike(String value) {
            addCriterion("productOldPrice not like", value, "productoldprice");
            return (Criteria) this;
        }

        public Criteria andProductoldpriceIn(List<String> values) {
            addCriterion("productOldPrice in", values, "productoldprice");
            return (Criteria) this;
        }

        public Criteria andProductoldpriceNotIn(List<String> values) {
            addCriterion("productOldPrice not in", values, "productoldprice");
            return (Criteria) this;
        }

        public Criteria andProductoldpriceBetween(String value1, String value2) {
            addCriterion("productOldPrice between", value1, value2, "productoldprice");
            return (Criteria) this;
        }

        public Criteria andProductoldpriceNotBetween(String value1, String value2) {
            addCriterion("productOldPrice not between", value1, value2, "productoldprice");
            return (Criteria) this;
        }

        public Criteria andProductnewpriceIsNull() {
            addCriterion("productNewPrice is null");
            return (Criteria) this;
        }

        public Criteria andProductnewpriceIsNotNull() {
            addCriterion("productNewPrice is not null");
            return (Criteria) this;
        }

        public Criteria andProductnewpriceEqualTo(String value) {
            addCriterion("productNewPrice =", value, "productnewprice");
            return (Criteria) this;
        }

        public Criteria andProductnewpriceNotEqualTo(String value) {
            addCriterion("productNewPrice <>", value, "productnewprice");
            return (Criteria) this;
        }

        public Criteria andProductnewpriceGreaterThan(String value) {
            addCriterion("productNewPrice >", value, "productnewprice");
            return (Criteria) this;
        }

        public Criteria andProductnewpriceGreaterThanOrEqualTo(String value) {
            addCriterion("productNewPrice >=", value, "productnewprice");
            return (Criteria) this;
        }

        public Criteria andProductnewpriceLessThan(String value) {
            addCriterion("productNewPrice <", value, "productnewprice");
            return (Criteria) this;
        }

        public Criteria andProductnewpriceLessThanOrEqualTo(String value) {
            addCriterion("productNewPrice <=", value, "productnewprice");
            return (Criteria) this;
        }

        public Criteria andProductnewpriceLike(String value) {
            addCriterion("productNewPrice like", value, "productnewprice");
            return (Criteria) this;
        }

        public Criteria andProductnewpriceNotLike(String value) {
            addCriterion("productNewPrice not like", value, "productnewprice");
            return (Criteria) this;
        }

        public Criteria andProductnewpriceIn(List<String> values) {
            addCriterion("productNewPrice in", values, "productnewprice");
            return (Criteria) this;
        }

        public Criteria andProductnewpriceNotIn(List<String> values) {
            addCriterion("productNewPrice not in", values, "productnewprice");
            return (Criteria) this;
        }

        public Criteria andProductnewpriceBetween(String value1, String value2) {
            addCriterion("productNewPrice between", value1, value2, "productnewprice");
            return (Criteria) this;
        }

        public Criteria andProductnewpriceNotBetween(String value1, String value2) {
            addCriterion("productNewPrice not between", value1, value2, "productnewprice");
            return (Criteria) this;
        }

        public Criteria andProductcategoryidIsNull() {
            addCriterion("productCategoryId is null");
            return (Criteria) this;
        }

        public Criteria andProductcategoryidIsNotNull() {
            addCriterion("productCategoryId is not null");
            return (Criteria) this;
        }

        public Criteria andProductcategoryidEqualTo(Integer value) {
            addCriterion("productCategoryId =", value, "productcategoryid");
            return (Criteria) this;
        }

        public Criteria andProductcategoryidNotEqualTo(Integer value) {
            addCriterion("productCategoryId <>", value, "productcategoryid");
            return (Criteria) this;
        }

        public Criteria andProductcategoryidGreaterThan(Integer value) {
            addCriterion("productCategoryId >", value, "productcategoryid");
            return (Criteria) this;
        }

        public Criteria andProductcategoryidGreaterThanOrEqualTo(Integer value) {
            addCriterion("productCategoryId >=", value, "productcategoryid");
            return (Criteria) this;
        }

        public Criteria andProductcategoryidLessThan(Integer value) {
            addCriterion("productCategoryId <", value, "productcategoryid");
            return (Criteria) this;
        }

        public Criteria andProductcategoryidLessThanOrEqualTo(Integer value) {
            addCriterion("productCategoryId <=", value, "productcategoryid");
            return (Criteria) this;
        }

        public Criteria andProductcategoryidIn(List<Integer> values) {
            addCriterion("productCategoryId in", values, "productcategoryid");
            return (Criteria) this;
        }

        public Criteria andProductcategoryidNotIn(List<Integer> values) {
            addCriterion("productCategoryId not in", values, "productcategoryid");
            return (Criteria) this;
        }

        public Criteria andProductcategoryidBetween(Integer value1, Integer value2) {
            addCriterion("productCategoryId between", value1, value2, "productcategoryid");
            return (Criteria) this;
        }

        public Criteria andProductcategoryidNotBetween(Integer value1, Integer value2) {
            addCriterion("productCategoryId not between", value1, value2, "productcategoryid");
            return (Criteria) this;
        }

        public Criteria andShopidIsNull() {
            addCriterion("shopId is null");
            return (Criteria) this;
        }

        public Criteria andShopidIsNotNull() {
            addCriterion("shopId is not null");
            return (Criteria) this;
        }

        public Criteria andShopidEqualTo(Integer value) {
            addCriterion("shopId =", value, "shopid");
            return (Criteria) this;
        }

        public Criteria andShopidNotEqualTo(Integer value) {
            addCriterion("shopId <>", value, "shopid");
            return (Criteria) this;
        }

        public Criteria andShopidGreaterThan(Integer value) {
            addCriterion("shopId >", value, "shopid");
            return (Criteria) this;
        }

        public Criteria andShopidGreaterThanOrEqualTo(Integer value) {
            addCriterion("shopId >=", value, "shopid");
            return (Criteria) this;
        }

        public Criteria andShopidLessThan(Integer value) {
            addCriterion("shopId <", value, "shopid");
            return (Criteria) this;
        }

        public Criteria andShopidLessThanOrEqualTo(Integer value) {
            addCriterion("shopId <=", value, "shopid");
            return (Criteria) this;
        }

        public Criteria andShopidIn(List<Integer> values) {
            addCriterion("shopId in", values, "shopid");
            return (Criteria) this;
        }

        public Criteria andShopidNotIn(List<Integer> values) {
            addCriterion("shopId not in", values, "shopid");
            return (Criteria) this;
        }

        public Criteria andShopidBetween(Integer value1, Integer value2) {
            addCriterion("shopId between", value1, value2, "shopid");
            return (Criteria) this;
        }

        public Criteria andShopidNotBetween(Integer value1, Integer value2) {
            addCriterion("shopId not between", value1, value2, "shopid");
            return (Criteria) this;
        }

        public Criteria andProductstatusIsNull() {
            addCriterion("productStatus is null");
            return (Criteria) this;
        }

        public Criteria andProductstatusIsNotNull() {
            addCriterion("productStatus is not null");
            return (Criteria) this;
        }

        public Criteria andProductstatusEqualTo(Integer value) {
            addCriterion("productStatus =", value, "productstatus");
            return (Criteria) this;
        }

        public Criteria andProductstatusNotEqualTo(Integer value) {
            addCriterion("productStatus <>", value, "productstatus");
            return (Criteria) this;
        }

        public Criteria andProductstatusGreaterThan(Integer value) {
            addCriterion("productStatus >", value, "productstatus");
            return (Criteria) this;
        }

        public Criteria andProductstatusGreaterThanOrEqualTo(Integer value) {
            addCriterion("productStatus >=", value, "productstatus");
            return (Criteria) this;
        }

        public Criteria andProductstatusLessThan(Integer value) {
            addCriterion("productStatus <", value, "productstatus");
            return (Criteria) this;
        }

        public Criteria andProductstatusLessThanOrEqualTo(Integer value) {
            addCriterion("productStatus <=", value, "productstatus");
            return (Criteria) this;
        }

        public Criteria andProductstatusIn(List<Integer> values) {
            addCriterion("productStatus in", values, "productstatus");
            return (Criteria) this;
        }

        public Criteria andProductstatusNotIn(List<Integer> values) {
            addCriterion("productStatus not in", values, "productstatus");
            return (Criteria) this;
        }

        public Criteria andProductstatusBetween(Integer value1, Integer value2) {
            addCriterion("productStatus between", value1, value2, "productstatus");
            return (Criteria) this;
        }

        public Criteria andProductstatusNotBetween(Integer value1, Integer value2) {
            addCriterion("productStatus not between", value1, value2, "productstatus");
            return (Criteria) this;
        }

        public Criteria andProductupdatetimeIsNull() {
            addCriterion("productUpdateTime is null");
            return (Criteria) this;
        }

        public Criteria andProductupdatetimeIsNotNull() {
            addCriterion("productUpdateTime is not null");
            return (Criteria) this;
        }

        public Criteria andProductupdatetimeEqualTo(Date value) {
            addCriterion("productUpdateTime =", value, "productupdatetime");
            return (Criteria) this;
        }

        public Criteria andProductupdatetimeNotEqualTo(Date value) {
            addCriterion("productUpdateTime <>", value, "productupdatetime");
            return (Criteria) this;
        }

        public Criteria andProductupdatetimeGreaterThan(Date value) {
            addCriterion("productUpdateTime >", value, "productupdatetime");
            return (Criteria) this;
        }

        public Criteria andProductupdatetimeGreaterThanOrEqualTo(Date value) {
            addCriterion("productUpdateTime >=", value, "productupdatetime");
            return (Criteria) this;
        }

        public Criteria andProductupdatetimeLessThan(Date value) {
            addCriterion("productUpdateTime <", value, "productupdatetime");
            return (Criteria) this;
        }

        public Criteria andProductupdatetimeLessThanOrEqualTo(Date value) {
            addCriterion("productUpdateTime <=", value, "productupdatetime");
            return (Criteria) this;
        }

        public Criteria andProductupdatetimeIn(List<Date> values) {
            addCriterion("productUpdateTime in", values, "productupdatetime");
            return (Criteria) this;
        }

        public Criteria andProductupdatetimeNotIn(List<Date> values) {
            addCriterion("productUpdateTime not in", values, "productupdatetime");
            return (Criteria) this;
        }

        public Criteria andProductupdatetimeBetween(Date value1, Date value2) {
            addCriterion("productUpdateTime between", value1, value2, "productupdatetime");
            return (Criteria) this;
        }

        public Criteria andProductupdatetimeNotBetween(Date value1, Date value2) {
            addCriterion("productUpdateTime not between", value1, value2, "productupdatetime");
            return (Criteria) this;
        }

        public Criteria andProductcreatetimeIsNull() {
            addCriterion("productCreateTime is null");
            return (Criteria) this;
        }

        public Criteria andProductcreatetimeIsNotNull() {
            addCriterion("productCreateTime is not null");
            return (Criteria) this;
        }

        public Criteria andProductcreatetimeEqualTo(Date value) {
            addCriterion("productCreateTime =", value, "productcreatetime");
            return (Criteria) this;
        }

        public Criteria andProductcreatetimeNotEqualTo(Date value) {
            addCriterion("productCreateTime <>", value, "productcreatetime");
            return (Criteria) this;
        }

        public Criteria andProductcreatetimeGreaterThan(Date value) {
            addCriterion("productCreateTime >", value, "productcreatetime");
            return (Criteria) this;
        }

        public Criteria andProductcreatetimeGreaterThanOrEqualTo(Date value) {
            addCriterion("productCreateTime >=", value, "productcreatetime");
            return (Criteria) this;
        }

        public Criteria andProductcreatetimeLessThan(Date value) {
            addCriterion("productCreateTime <", value, "productcreatetime");
            return (Criteria) this;
        }

        public Criteria andProductcreatetimeLessThanOrEqualTo(Date value) {
            addCriterion("productCreateTime <=", value, "productcreatetime");
            return (Criteria) this;
        }

        public Criteria andProductcreatetimeIn(List<Date> values) {
            addCriterion("productCreateTime in", values, "productcreatetime");
            return (Criteria) this;
        }

        public Criteria andProductcreatetimeNotIn(List<Date> values) {
            addCriterion("productCreateTime not in", values, "productcreatetime");
            return (Criteria) this;
        }

        public Criteria andProductcreatetimeBetween(Date value1, Date value2) {
            addCriterion("productCreateTime between", value1, value2, "productcreatetime");
            return (Criteria) this;
        }

        public Criteria andProductcreatetimeNotBetween(Date value1, Date value2) {
            addCriterion("productCreateTime not between", value1, value2, "productcreatetime");
            return (Criteria) this;
        }

        public Criteria andProductpriorityIsNull() {
            addCriterion("productPriority is null");
            return (Criteria) this;
        }

        public Criteria andProductpriorityIsNotNull() {
            addCriterion("productPriority is not null");
            return (Criteria) this;
        }

        public Criteria andProductpriorityEqualTo(Integer value) {
            addCriterion("productPriority =", value, "productpriority");
            return (Criteria) this;
        }

        public Criteria andProductpriorityNotEqualTo(Integer value) {
            addCriterion("productPriority <>", value, "productpriority");
            return (Criteria) this;
        }

        public Criteria andProductpriorityGreaterThan(Integer value) {
            addCriterion("productPriority >", value, "productpriority");
            return (Criteria) this;
        }

        public Criteria andProductpriorityGreaterThanOrEqualTo(Integer value) {
            addCriterion("productPriority >=", value, "productpriority");
            return (Criteria) this;
        }

        public Criteria andProductpriorityLessThan(Integer value) {
            addCriterion("productPriority <", value, "productpriority");
            return (Criteria) this;
        }

        public Criteria andProductpriorityLessThanOrEqualTo(Integer value) {
            addCriterion("productPriority <=", value, "productpriority");
            return (Criteria) this;
        }

        public Criteria andProductpriorityIn(List<Integer> values) {
            addCriterion("productPriority in", values, "productpriority");
            return (Criteria) this;
        }

        public Criteria andProductpriorityNotIn(List<Integer> values) {
            addCriterion("productPriority not in", values, "productpriority");
            return (Criteria) this;
        }

        public Criteria andProductpriorityBetween(Integer value1, Integer value2) {
            addCriterion("productPriority between", value1, value2, "productpriority");
            return (Criteria) this;
        }

        public Criteria andProductpriorityNotBetween(Integer value1, Integer value2) {
            addCriterion("productPriority not between", value1, value2, "productpriority");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table product
     *
     * @mbg.generated do_not_delete_during_merge Tue May 14 10:43:09 CST 2019
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table product
     *
     * @mbg.generated Tue May 14 10:43:09 CST 2019
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }


    }
}