package club.bagedate.o2o.entity;

import java.util.Date;

public class Product {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.productId
     *
     * @mbg.generated Tue May 14 10:48:08 CST 2019
     */
    private Integer productid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.productName
     *
     * @mbg.generated Tue May 14 10:48:08 CST 2019
     */
    private String productname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.productDesc
     *
     * @mbg.generated Tue May 14 10:48:08 CST 2019
     */
    private String productdesc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.productPlace
     *
     * @mbg.generated Tue May 14 10:48:08 CST 2019
     */
    private String productplace;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.productOldPrice
     *
     * @mbg.generated Tue May 14 10:48:08 CST 2019
     */
    private String productoldprice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.productNewPrice
     *
     * @mbg.generated Tue May 14 10:48:08 CST 2019
     */
    private String productnewprice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.productCategoryId
     *
     * @mbg.generated Tue May 14 10:48:08 CST 2019
     */
    private Integer productcategoryid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.shopId
     *
     * @mbg.generated Tue May 14 10:48:08 CST 2019
     */
    private Integer shopid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.productStatus
     *
     * @mbg.generated Tue May 14 10:48:08 CST 2019
     */
    private Integer productstatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.productUpdateTime
     *
     * @mbg.generated Tue May 14 10:48:08 CST 2019
     */
    private Date productupdatetime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.productCreateTime
     *
     * @mbg.generated Tue May 14 10:48:08 CST 2019
     */
    private Date productcreatetime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.productPriority
     *
     * @mbg.generated Tue May 14 10:48:08 CST 2019
     */
    private Integer productpriority;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.productId
     *
     * @return the value of product.productId
     *
     * @mbg.generated Tue May 14 10:48:08 CST 2019
     */
    public Integer getProductid() {
        return productid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.productId
     *
     * @param productid the value for product.productId
     *
     * @mbg.generated Tue May 14 10:48:08 CST 2019
     */
    public void setProductid(Integer productid) {
        this.productid = productid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.productName
     *
     * @return the value of product.productName
     *
     * @mbg.generated Tue May 14 10:48:08 CST 2019
     */
    public String getProductname() {
        return productname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.productName
     *
     * @param productname the value for product.productName
     *
     * @mbg.generated Tue May 14 10:48:08 CST 2019
     */
    public void setProductname(String productname) {
        this.productname = productname == null ? null : productname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.productDesc
     *
     * @return the value of product.productDesc
     *
     * @mbg.generated Tue May 14 10:48:08 CST 2019
     */
    public String getProductdesc() {
        return productdesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.productDesc
     *
     * @param productdesc the value for product.productDesc
     *
     * @mbg.generated Tue May 14 10:48:08 CST 2019
     */
    public void setProductdesc(String productdesc) {
        this.productdesc = productdesc == null ? null : productdesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.productPlace
     *
     * @return the value of product.productPlace
     *
     * @mbg.generated Tue May 14 10:48:08 CST 2019
     */
    public String getProductplace() {
        return productplace;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.productPlace
     *
     * @param productplace the value for product.productPlace
     *
     * @mbg.generated Tue May 14 10:48:08 CST 2019
     */
    public void setProductplace(String productplace) {
        this.productplace = productplace == null ? null : productplace.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.productOldPrice
     *
     * @return the value of product.productOldPrice
     *
     * @mbg.generated Tue May 14 10:48:08 CST 2019
     */
    public String getProductoldprice() {
        return productoldprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.productOldPrice
     *
     * @param productoldprice the value for product.productOldPrice
     *
     * @mbg.generated Tue May 14 10:48:08 CST 2019
     */
    public void setProductoldprice(String productoldprice) {
        this.productoldprice = productoldprice == null ? null : productoldprice.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.productNewPrice
     *
     * @return the value of product.productNewPrice
     *
     * @mbg.generated Tue May 14 10:48:08 CST 2019
     */
    public String getProductnewprice() {
        return productnewprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.productNewPrice
     *
     * @param productnewprice the value for product.productNewPrice
     *
     * @mbg.generated Tue May 14 10:48:08 CST 2019
     */
    public void setProductnewprice(String productnewprice) {
        this.productnewprice = productnewprice == null ? null : productnewprice.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.productCategoryId
     *
     * @return the value of product.productCategoryId
     *
     * @mbg.generated Tue May 14 10:48:08 CST 2019
     */
    public Integer getProductcategoryid() {
        return productcategoryid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.productCategoryId
     *
     * @param productcategoryid the value for product.productCategoryId
     *
     * @mbg.generated Tue May 14 10:48:08 CST 2019
     */
    public void setProductcategoryid(Integer productcategoryid) {
        this.productcategoryid = productcategoryid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.shopId
     *
     * @return the value of product.shopId
     *
     * @mbg.generated Tue May 14 10:48:08 CST 2019
     */
    public Integer getShopid() {
        return shopid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.shopId
     *
     * @param shopid the value for product.shopId
     *
     * @mbg.generated Tue May 14 10:48:08 CST 2019
     */
    public void setShopid(Integer shopid) {
        this.shopid = shopid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.productStatus
     *
     * @return the value of product.productStatus
     *
     * @mbg.generated Tue May 14 10:48:08 CST 2019
     */
    public Integer getProductstatus() {
        return productstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.productStatus
     *
     * @param productstatus the value for product.productStatus
     *
     * @mbg.generated Tue May 14 10:48:08 CST 2019
     */
    public void setProductstatus(Integer productstatus) {
        this.productstatus = productstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.productUpdateTime
     *
     * @return the value of product.productUpdateTime
     *
     * @mbg.generated Tue May 14 10:48:08 CST 2019
     */
    public Date getProductupdatetime() {
        return productupdatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.productUpdateTime
     *
     * @param productupdatetime the value for product.productUpdateTime
     *
     * @mbg.generated Tue May 14 10:48:08 CST 2019
     */
    public void setProductupdatetime(Date productupdatetime) {
        this.productupdatetime = productupdatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.productCreateTime
     *
     * @return the value of product.productCreateTime
     *
     * @mbg.generated Tue May 14 10:48:08 CST 2019
     */
    public Date getProductcreatetime() {
        return productcreatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.productCreateTime
     *
     * @param productcreatetime the value for product.productCreateTime
     *
     * @mbg.generated Tue May 14 10:48:08 CST 2019
     */
    public void setProductcreatetime(Date productcreatetime) {
        this.productcreatetime = productcreatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.productPriority
     *
     * @return the value of product.productPriority
     *
     * @mbg.generated Tue May 14 10:48:08 CST 2019
     */
    public Integer getProductpriority() {
        return productpriority;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.productPriority
     *
     * @param productpriority the value for product.productPriority
     *
     * @mbg.generated Tue May 14 10:48:08 CST 2019
     */
    public void setProductpriority(Integer productpriority) {
        this.productpriority = productpriority;
    }
}