package club.bagedate.o2o.entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class ProductImgExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table productimg
     *
     * @mbg.generated Tue May 14 10:43:09 CST 2019
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table productimg
     *
     * @mbg.generated Tue May 14 10:43:09 CST 2019
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table productimg
     *
     * @mbg.generated Tue May 14 10:43:09 CST 2019
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table productimg
     *
     * @mbg.generated Tue May 14 10:43:09 CST 2019
     */
    public ProductImgExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table productimg
     *
     * @mbg.generated Tue May 14 10:43:09 CST 2019
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table productimg
     *
     * @mbg.generated Tue May 14 10:43:09 CST 2019
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table productimg
     *
     * @mbg.generated Tue May 14 10:43:09 CST 2019
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table productimg
     *
     * @mbg.generated Tue May 14 10:43:09 CST 2019
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table productimg
     *
     * @mbg.generated Tue May 14 10:43:09 CST 2019
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table productimg
     *
     * @mbg.generated Tue May 14 10:43:09 CST 2019
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table productimg
     *
     * @mbg.generated Tue May 14 10:43:09 CST 2019
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table productimg
     *
     * @mbg.generated Tue May 14 10:43:09 CST 2019
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table productimg
     *
     * @mbg.generated Tue May 14 10:43:09 CST 2019
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table productimg
     *
     * @mbg.generated Tue May 14 10:43:09 CST 2019
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table productimg
     *
     * @mbg.generated Tue May 14 10:43:09 CST 2019
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andProductimgidIsNull() {
            addCriterion("productImgId is null");
            return (Criteria) this;
        }

        public Criteria andProductimgidIsNotNull() {
            addCriterion("productImgId is not null");
            return (Criteria) this;
        }

        public Criteria andProductimgidEqualTo(Integer value) {
            addCriterion("productImgId =", value, "productimgid");
            return (Criteria) this;
        }

        public Criteria andProductimgidNotEqualTo(Integer value) {
            addCriterion("productImgId <>", value, "productimgid");
            return (Criteria) this;
        }

        public Criteria andProductimgidGreaterThan(Integer value) {
            addCriterion("productImgId >", value, "productimgid");
            return (Criteria) this;
        }

        public Criteria andProductimgidGreaterThanOrEqualTo(Integer value) {
            addCriterion("productImgId >=", value, "productimgid");
            return (Criteria) this;
        }

        public Criteria andProductimgidLessThan(Integer value) {
            addCriterion("productImgId <", value, "productimgid");
            return (Criteria) this;
        }

        public Criteria andProductimgidLessThanOrEqualTo(Integer value) {
            addCriterion("productImgId <=", value, "productimgid");
            return (Criteria) this;
        }

        public Criteria andProductimgidIn(List<Integer> values) {
            addCriterion("productImgId in", values, "productimgid");
            return (Criteria) this;
        }

        public Criteria andProductimgidNotIn(List<Integer> values) {
            addCriterion("productImgId not in", values, "productimgid");
            return (Criteria) this;
        }

        public Criteria andProductimgidBetween(Integer value1, Integer value2) {
            addCriterion("productImgId between", value1, value2, "productimgid");
            return (Criteria) this;
        }

        public Criteria andProductimgidNotBetween(Integer value1, Integer value2) {
            addCriterion("productImgId not between", value1, value2, "productimgid");
            return (Criteria) this;
        }

        public Criteria andProductimgplaceIsNull() {
            addCriterion("productImgPlace is null");
            return (Criteria) this;
        }

        public Criteria andProductimgplaceIsNotNull() {
            addCriterion("productImgPlace is not null");
            return (Criteria) this;
        }

        public Criteria andProductimgplaceEqualTo(String value) {
            addCriterion("productImgPlace =", value, "productimgplace");
            return (Criteria) this;
        }

        public Criteria andProductimgplaceNotEqualTo(String value) {
            addCriterion("productImgPlace <>", value, "productimgplace");
            return (Criteria) this;
        }

        public Criteria andProductimgplaceGreaterThan(String value) {
            addCriterion("productImgPlace >", value, "productimgplace");
            return (Criteria) this;
        }

        public Criteria andProductimgplaceGreaterThanOrEqualTo(String value) {
            addCriterion("productImgPlace >=", value, "productimgplace");
            return (Criteria) this;
        }

        public Criteria andProductimgplaceLessThan(String value) {
            addCriterion("productImgPlace <", value, "productimgplace");
            return (Criteria) this;
        }

        public Criteria andProductimgplaceLessThanOrEqualTo(String value) {
            addCriterion("productImgPlace <=", value, "productimgplace");
            return (Criteria) this;
        }

        public Criteria andProductimgplaceLike(String value) {
            addCriterion("productImgPlace like", value, "productimgplace");
            return (Criteria) this;
        }

        public Criteria andProductimgplaceNotLike(String value) {
            addCriterion("productImgPlace not like", value, "productimgplace");
            return (Criteria) this;
        }

        public Criteria andProductimgplaceIn(List<String> values) {
            addCriterion("productImgPlace in", values, "productimgplace");
            return (Criteria) this;
        }

        public Criteria andProductimgplaceNotIn(List<String> values) {
            addCriterion("productImgPlace not in", values, "productimgplace");
            return (Criteria) this;
        }

        public Criteria andProductimgplaceBetween(String value1, String value2) {
            addCriterion("productImgPlace between", value1, value2, "productimgplace");
            return (Criteria) this;
        }

        public Criteria andProductimgplaceNotBetween(String value1, String value2) {
            addCriterion("productImgPlace not between", value1, value2, "productimgplace");
            return (Criteria) this;
        }

        public Criteria andProductimgdescIsNull() {
            addCriterion("productImgDesc is null");
            return (Criteria) this;
        }

        public Criteria andProductimgdescIsNotNull() {
            addCriterion("productImgDesc is not null");
            return (Criteria) this;
        }

        public Criteria andProductimgdescEqualTo(String value) {
            addCriterion("productImgDesc =", value, "productimgdesc");
            return (Criteria) this;
        }

        public Criteria andProductimgdescNotEqualTo(String value) {
            addCriterion("productImgDesc <>", value, "productimgdesc");
            return (Criteria) this;
        }

        public Criteria andProductimgdescGreaterThan(String value) {
            addCriterion("productImgDesc >", value, "productimgdesc");
            return (Criteria) this;
        }

        public Criteria andProductimgdescGreaterThanOrEqualTo(String value) {
            addCriterion("productImgDesc >=", value, "productimgdesc");
            return (Criteria) this;
        }

        public Criteria andProductimgdescLessThan(String value) {
            addCriterion("productImgDesc <", value, "productimgdesc");
            return (Criteria) this;
        }

        public Criteria andProductimgdescLessThanOrEqualTo(String value) {
            addCriterion("productImgDesc <=", value, "productimgdesc");
            return (Criteria) this;
        }

        public Criteria andProductimgdescLike(String value) {
            addCriterion("productImgDesc like", value, "productimgdesc");
            return (Criteria) this;
        }

        public Criteria andProductimgdescNotLike(String value) {
            addCriterion("productImgDesc not like", value, "productimgdesc");
            return (Criteria) this;
        }

        public Criteria andProductimgdescIn(List<String> values) {
            addCriterion("productImgDesc in", values, "productimgdesc");
            return (Criteria) this;
        }

        public Criteria andProductimgdescNotIn(List<String> values) {
            addCriterion("productImgDesc not in", values, "productimgdesc");
            return (Criteria) this;
        }

        public Criteria andProductimgdescBetween(String value1, String value2) {
            addCriterion("productImgDesc between", value1, value2, "productimgdesc");
            return (Criteria) this;
        }

        public Criteria andProductimgdescNotBetween(String value1, String value2) {
            addCriterion("productImgDesc not between", value1, value2, "productimgdesc");
            return (Criteria) this;
        }

        public Criteria andProductimgpriorityIsNull() {
            addCriterion("productImgPriority is null");
            return (Criteria) this;
        }

        public Criteria andProductimgpriorityIsNotNull() {
            addCriterion("productImgPriority is not null");
            return (Criteria) this;
        }

        public Criteria andProductimgpriorityEqualTo(Integer value) {
            addCriterion("productImgPriority =", value, "productimgpriority");
            return (Criteria) this;
        }

        public Criteria andProductimgpriorityNotEqualTo(Integer value) {
            addCriterion("productImgPriority <>", value, "productimgpriority");
            return (Criteria) this;
        }

        public Criteria andProductimgpriorityGreaterThan(Integer value) {
            addCriterion("productImgPriority >", value, "productimgpriority");
            return (Criteria) this;
        }

        public Criteria andProductimgpriorityGreaterThanOrEqualTo(Integer value) {
            addCriterion("productImgPriority >=", value, "productimgpriority");
            return (Criteria) this;
        }

        public Criteria andProductimgpriorityLessThan(Integer value) {
            addCriterion("productImgPriority <", value, "productimgpriority");
            return (Criteria) this;
        }

        public Criteria andProductimgpriorityLessThanOrEqualTo(Integer value) {
            addCriterion("productImgPriority <=", value, "productimgpriority");
            return (Criteria) this;
        }

        public Criteria andProductimgpriorityIn(List<Integer> values) {
            addCriterion("productImgPriority in", values, "productimgpriority");
            return (Criteria) this;
        }

        public Criteria andProductimgpriorityNotIn(List<Integer> values) {
            addCriterion("productImgPriority not in", values, "productimgpriority");
            return (Criteria) this;
        }

        public Criteria andProductimgpriorityBetween(Integer value1, Integer value2) {
            addCriterion("productImgPriority between", value1, value2, "productimgpriority");
            return (Criteria) this;
        }

        public Criteria andProductimgpriorityNotBetween(Integer value1, Integer value2) {
            addCriterion("productImgPriority not between", value1, value2, "productimgpriority");
            return (Criteria) this;
        }

        public Criteria andProductimgcreatetimeIsNull() {
            addCriterion("productImgCreateTime is null");
            return (Criteria) this;
        }

        public Criteria andProductimgcreatetimeIsNotNull() {
            addCriterion("productImgCreateTime is not null");
            return (Criteria) this;
        }

        public Criteria andProductimgcreatetimeEqualTo(Date value) {
            addCriterion("productImgCreateTime =", value, "productimgcreatetime");
            return (Criteria) this;
        }

        public Criteria andProductimgcreatetimeNotEqualTo(Date value) {
            addCriterion("productImgCreateTime <>", value, "productimgcreatetime");
            return (Criteria) this;
        }

        public Criteria andProductimgcreatetimeGreaterThan(Date value) {
            addCriterion("productImgCreateTime >", value, "productimgcreatetime");
            return (Criteria) this;
        }

        public Criteria andProductimgcreatetimeGreaterThanOrEqualTo(Date value) {
            addCriterion("productImgCreateTime >=", value, "productimgcreatetime");
            return (Criteria) this;
        }

        public Criteria andProductimgcreatetimeLessThan(Date value) {
            addCriterion("productImgCreateTime <", value, "productimgcreatetime");
            return (Criteria) this;
        }

        public Criteria andProductimgcreatetimeLessThanOrEqualTo(Date value) {
            addCriterion("productImgCreateTime <=", value, "productimgcreatetime");
            return (Criteria) this;
        }

        public Criteria andProductimgcreatetimeIn(List<Date> values) {
            addCriterion("productImgCreateTime in", values, "productimgcreatetime");
            return (Criteria) this;
        }

        public Criteria andProductimgcreatetimeNotIn(List<Date> values) {
            addCriterion("productImgCreateTime not in", values, "productimgcreatetime");
            return (Criteria) this;
        }

        public Criteria andProductimgcreatetimeBetween(Date value1, Date value2) {
            addCriterion("productImgCreateTime between", value1, value2, "productimgcreatetime");
            return (Criteria) this;
        }

        public Criteria andProductimgcreatetimeNotBetween(Date value1, Date value2) {
            addCriterion("productImgCreateTime not between", value1, value2, "productimgcreatetime");
            return (Criteria) this;
        }

        public Criteria andProductidIsNull() {
            addCriterion("productId is null");
            return (Criteria) this;
        }

        public Criteria andProductidIsNotNull() {
            addCriterion("productId is not null");
            return (Criteria) this;
        }

        public Criteria andProductidEqualTo(Integer value) {
            addCriterion("productId =", value, "productid");
            return (Criteria) this;
        }

        public Criteria andProductidNotEqualTo(Integer value) {
            addCriterion("productId <>", value, "productid");
            return (Criteria) this;
        }

        public Criteria andProductidGreaterThan(Integer value) {
            addCriterion("productId >", value, "productid");
            return (Criteria) this;
        }

        public Criteria andProductidGreaterThanOrEqualTo(Integer value) {
            addCriterion("productId >=", value, "productid");
            return (Criteria) this;
        }

        public Criteria andProductidLessThan(Integer value) {
            addCriterion("productId <", value, "productid");
            return (Criteria) this;
        }

        public Criteria andProductidLessThanOrEqualTo(Integer value) {
            addCriterion("productId <=", value, "productid");
            return (Criteria) this;
        }

        public Criteria andProductidIn(List<Integer> values) {
            addCriterion("productId in", values, "productid");
            return (Criteria) this;
        }

        public Criteria andProductidNotIn(List<Integer> values) {
            addCriterion("productId not in", values, "productid");
            return (Criteria) this;
        }

        public Criteria andProductidBetween(Integer value1, Integer value2) {
            addCriterion("productId between", value1, value2, "productid");
            return (Criteria) this;
        }

        public Criteria andProductidNotBetween(Integer value1, Integer value2) {
            addCriterion("productId not between", value1, value2, "productid");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table productimg
     *
     * @mbg.generated do_not_delete_during_merge Tue May 14 10:43:09 CST 2019
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table productimg
     *
     * @mbg.generated Tue May 14 10:43:09 CST 2019
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}