package club.bagedate.o2o.entity;

import java.util.Date;

public class ProductCategory {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column productcategory.productCategoryId
     *
     * @mbg.generated Tue May 14 10:43:09 CST 2019
     */
    private Integer productcategoryid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column productcategory.shopId
     *
     * @mbg.generated Tue May 14 10:43:09 CST 2019
     */
    private Integer shopid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column productcategory.productCategoryName
     *
     * @mbg.generated Tue May 14 10:43:09 CST 2019
     */
    private String productcategoryname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column productcategory.productCategoryPriority
     *
     * @mbg.generated Tue May 14 10:43:09 CST 2019
     */
    private Integer productcategorypriority;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column productcategory.productCategoryCreateTime
     *
     * @mbg.generated Tue May 14 10:43:09 CST 2019
     */
    private Date productcategorycreatetime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column productcategory.productCategoryId
     *
     * @return the value of productcategory.productCategoryId
     *
     * @mbg.generated Tue May 14 10:43:09 CST 2019
     */
    public Integer getProductcategoryid() {
        return productcategoryid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column productcategory.productCategoryId
     *
     * @param productcategoryid the value for productcategory.productCategoryId
     *
     * @mbg.generated Tue May 14 10:43:09 CST 2019
     */
    public void setProductcategoryid(Integer productcategoryid) {
        this.productcategoryid = productcategoryid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column productcategory.shopId
     *
     * @return the value of productcategory.shopId
     *
     * @mbg.generated Tue May 14 10:43:09 CST 2019
     */
    public Integer getShopid() {
        return shopid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column productcategory.shopId
     *
     * @param shopid the value for productcategory.shopId
     *
     * @mbg.generated Tue May 14 10:43:09 CST 2019
     */
    public void setShopid(Integer shopid) {
        this.shopid = shopid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column productcategory.productCategoryName
     *
     * @return the value of productcategory.productCategoryName
     *
     * @mbg.generated Tue May 14 10:43:09 CST 2019
     */
    public String getProductcategoryname() {
        return productcategoryname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column productcategory.productCategoryName
     *
     * @param productcategoryname the value for productcategory.productCategoryName
     *
     * @mbg.generated Tue May 14 10:43:09 CST 2019
     */
    public void setProductcategoryname(String productcategoryname) {
        this.productcategoryname = productcategoryname == null ? null : productcategoryname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column productcategory.productCategoryPriority
     *
     * @return the value of productcategory.productCategoryPriority
     *
     * @mbg.generated Tue May 14 10:43:09 CST 2019
     */
    public Integer getProductcategorypriority() {
        return productcategorypriority;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column productcategory.productCategoryPriority
     *
     * @param productcategorypriority the value for productcategory.productCategoryPriority
     *
     * @mbg.generated Tue May 14 10:43:09 CST 2019
     */
    public void setProductcategorypriority(Integer productcategorypriority) {
        this.productcategorypriority = productcategorypriority;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column productcategory.productCategoryCreateTime
     *
     * @return the value of productcategory.productCategoryCreateTime
     *
     * @mbg.generated Tue May 14 10:43:09 CST 2019
     */
    public Date getProductcategorycreatetime() {
        return productcategorycreatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column productcategory.productCategoryCreateTime
     *
     * @param productcategorycreatetime the value for productcategory.productCategoryCreateTime
     *
     * @mbg.generated Tue May 14 10:43:09 CST 2019
     */
    public void setProductcategorycreatetime(Date productcategorycreatetime) {
        this.productcategorycreatetime = productcategorycreatetime;
    }

    @Override
    public String toString() {
        return "ProductCategory{" +
                "productcategoryid=" + productcategoryid +
                ", shopid=" + shopid +
                ", productcategoryname='" + productcategoryname + '\'' +
                ", productcategorypriority=" + productcategorypriority +
                ", productcategorycreatetime=" + productcategorycreatetime +
                '}';
    }
}