package club.bagedate.o2o.entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class ShopCategoryExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table shopcategory
     *
     * @mbg.generated Tue May 14 10:43:09 CST 2019
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table shopcategory
     *
     * @mbg.generated Tue May 14 10:43:09 CST 2019
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table shopcategory
     *
     * @mbg.generated Tue May 14 10:43:09 CST 2019
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shopcategory
     *
     * @mbg.generated Tue May 14 10:43:09 CST 2019
     */
    public ShopCategoryExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shopcategory
     *
     * @mbg.generated Tue May 14 10:43:09 CST 2019
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shopcategory
     *
     * @mbg.generated Tue May 14 10:43:09 CST 2019
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shopcategory
     *
     * @mbg.generated Tue May 14 10:43:09 CST 2019
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shopcategory
     *
     * @mbg.generated Tue May 14 10:43:09 CST 2019
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shopcategory
     *
     * @mbg.generated Tue May 14 10:43:09 CST 2019
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shopcategory
     *
     * @mbg.generated Tue May 14 10:43:09 CST 2019
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shopcategory
     *
     * @mbg.generated Tue May 14 10:43:09 CST 2019
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shopcategory
     *
     * @mbg.generated Tue May 14 10:43:09 CST 2019
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shopcategory
     *
     * @mbg.generated Tue May 14 10:43:09 CST 2019
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shopcategory
     *
     * @mbg.generated Tue May 14 10:43:09 CST 2019
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table shopcategory
     *
     * @mbg.generated Tue May 14 10:43:09 CST 2019
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andShopcategoryidIsNull() {
            addCriterion("shopCategoryId is null");
            return (Criteria) this;
        }

        public Criteria andShopcategoryidIsNotNull() {
            addCriterion("shopCategoryId is not null");
            return (Criteria) this;
        }

        public Criteria andShopcategoryidEqualTo(Integer value) {
            addCriterion("shopCategoryId =", value, "shopcategoryid");
            return (Criteria) this;
        }

        public Criteria andShopcategoryidNotEqualTo(Integer value) {
            addCriterion("shopCategoryId <>", value, "shopcategoryid");
            return (Criteria) this;
        }

        public Criteria andShopcategoryidGreaterThan(Integer value) {
            addCriterion("shopCategoryId >", value, "shopcategoryid");
            return (Criteria) this;
        }

        public Criteria andShopcategoryidGreaterThanOrEqualTo(Integer value) {
            addCriterion("shopCategoryId >=", value, "shopcategoryid");
            return (Criteria) this;
        }

        public Criteria andShopcategoryidLessThan(Integer value) {
            addCriterion("shopCategoryId <", value, "shopcategoryid");
            return (Criteria) this;
        }

        public Criteria andShopcategoryidLessThanOrEqualTo(Integer value) {
            addCriterion("shopCategoryId <=", value, "shopcategoryid");
            return (Criteria) this;
        }

        public Criteria andShopcategoryidIn(List<Integer> values) {
            addCriterion("shopCategoryId in", values, "shopcategoryid");
            return (Criteria) this;
        }

        public Criteria andShopcategoryidNotIn(List<Integer> values) {
            addCriterion("shopCategoryId not in", values, "shopcategoryid");
            return (Criteria) this;
        }

        public Criteria andShopcategoryidBetween(Integer value1, Integer value2) {
            addCriterion("shopCategoryId between", value1, value2, "shopcategoryid");
            return (Criteria) this;
        }

        public Criteria andShopcategoryidNotBetween(Integer value1, Integer value2) {
            addCriterion("shopCategoryId not between", value1, value2, "shopcategoryid");
            return (Criteria) this;
        }

        public Criteria andShopcategorypriorityIsNull() {
            addCriterion("shopCategoryPriority is null");
            return (Criteria) this;
        }

        public Criteria andShopcategorypriorityIsNotNull() {
            addCriterion("shopCategoryPriority is not null");
            return (Criteria) this;
        }

        public Criteria andShopcategorypriorityEqualTo(Integer value) {
            addCriterion("shopCategoryPriority =", value, "shopcategorypriority");
            return (Criteria) this;
        }

        public Criteria andShopcategorypriorityNotEqualTo(Integer value) {
            addCriterion("shopCategoryPriority <>", value, "shopcategorypriority");
            return (Criteria) this;
        }

        public Criteria andShopcategorypriorityGreaterThan(Integer value) {
            addCriterion("shopCategoryPriority >", value, "shopcategorypriority");
            return (Criteria) this;
        }

        public Criteria andShopcategorypriorityGreaterThanOrEqualTo(Integer value) {
            addCriterion("shopCategoryPriority >=", value, "shopcategorypriority");
            return (Criteria) this;
        }

        public Criteria andShopcategorypriorityLessThan(Integer value) {
            addCriterion("shopCategoryPriority <", value, "shopcategorypriority");
            return (Criteria) this;
        }

        public Criteria andShopcategorypriorityLessThanOrEqualTo(Integer value) {
            addCriterion("shopCategoryPriority <=", value, "shopcategorypriority");
            return (Criteria) this;
        }

        public Criteria andShopcategorypriorityIn(List<Integer> values) {
            addCriterion("shopCategoryPriority in", values, "shopcategorypriority");
            return (Criteria) this;
        }

        public Criteria andShopcategorypriorityNotIn(List<Integer> values) {
            addCriterion("shopCategoryPriority not in", values, "shopcategorypriority");
            return (Criteria) this;
        }

        public Criteria andShopcategorypriorityBetween(Integer value1, Integer value2) {
            addCriterion("shopCategoryPriority between", value1, value2, "shopcategorypriority");
            return (Criteria) this;
        }

        public Criteria andShopcategorypriorityNotBetween(Integer value1, Integer value2) {
            addCriterion("shopCategoryPriority not between", value1, value2, "shopcategorypriority");
            return (Criteria) this;
        }

        public Criteria andShopcategoryparentidIsNull() {
            addCriterion("shopCategoryParentId is null");
            return (Criteria) this;
        }

        public Criteria andShopcategoryparentidIsNotNull() {
            addCriterion("shopCategoryParentId is not null");
            return (Criteria) this;
        }

        public Criteria andShopcategoryparentidEqualTo(Integer value) {
            addCriterion("shopCategoryParentId =", value, "shopcategoryparentid");
            return (Criteria) this;
        }

        public Criteria andShopcategoryparentidNotEqualTo(Integer value) {
            addCriterion("shopCategoryParentId <>", value, "shopcategoryparentid");
            return (Criteria) this;
        }

        public Criteria andShopcategoryparentidGreaterThan(Integer value) {
            addCriterion("shopCategoryParentId >", value, "shopcategoryparentid");
            return (Criteria) this;
        }

        public Criteria andShopcategoryparentidGreaterThanOrEqualTo(Integer value) {
            addCriterion("shopCategoryParentId >=", value, "shopcategoryparentid");
            return (Criteria) this;
        }

        public Criteria andShopcategoryparentidLessThan(Integer value) {
            addCriterion("shopCategoryParentId <", value, "shopcategoryparentid");
            return (Criteria) this;
        }

        public Criteria andShopcategoryparentidLessThanOrEqualTo(Integer value) {
            addCriterion("shopCategoryParentId <=", value, "shopcategoryparentid");
            return (Criteria) this;
        }

        public Criteria andShopcategoryparentidIn(List<Integer> values) {
            addCriterion("shopCategoryParentId in", values, "shopcategoryparentid");
            return (Criteria) this;
        }

        public Criteria andShopcategoryparentidNotIn(List<Integer> values) {
            addCriterion("shopCategoryParentId not in", values, "shopcategoryparentid");
            return (Criteria) this;
        }

        public Criteria andShopcategoryparentidBetween(Integer value1, Integer value2) {
            addCriterion("shopCategoryParentId between", value1, value2, "shopcategoryparentid");
            return (Criteria) this;
        }

        public Criteria andShopcategoryparentidNotBetween(Integer value1, Integer value2) {
            addCriterion("shopCategoryParentId not between", value1, value2, "shopcategoryparentid");
            return (Criteria) this;
        }

        public Criteria andShopcategorynameIsNull() {
            addCriterion("shopCategoryName is null");
            return (Criteria) this;
        }

        public Criteria andShopcategorynameIsNotNull() {
            addCriterion("shopCategoryName is not null");
            return (Criteria) this;
        }

        public Criteria andShopcategorynameEqualTo(String value) {
            addCriterion("shopCategoryName =", value, "shopcategoryname");
            return (Criteria) this;
        }

        public Criteria andShopcategorynameNotEqualTo(String value) {
            addCriterion("shopCategoryName <>", value, "shopcategoryname");
            return (Criteria) this;
        }

        public Criteria andShopcategorynameGreaterThan(String value) {
            addCriterion("shopCategoryName >", value, "shopcategoryname");
            return (Criteria) this;
        }

        public Criteria andShopcategorynameGreaterThanOrEqualTo(String value) {
            addCriterion("shopCategoryName >=", value, "shopcategoryname");
            return (Criteria) this;
        }

        public Criteria andShopcategorynameLessThan(String value) {
            addCriterion("shopCategoryName <", value, "shopcategoryname");
            return (Criteria) this;
        }

        public Criteria andShopcategorynameLessThanOrEqualTo(String value) {
            addCriterion("shopCategoryName <=", value, "shopcategoryname");
            return (Criteria) this;
        }

        public Criteria andShopcategorynameLike(String value) {
            addCriterion("shopCategoryName like", value, "shopcategoryname");
            return (Criteria) this;
        }

        public Criteria andShopcategorynameNotLike(String value) {
            addCriterion("shopCategoryName not like", value, "shopcategoryname");
            return (Criteria) this;
        }

        public Criteria andShopcategorynameIn(List<String> values) {
            addCriterion("shopCategoryName in", values, "shopcategoryname");
            return (Criteria) this;
        }

        public Criteria andShopcategorynameNotIn(List<String> values) {
            addCriterion("shopCategoryName not in", values, "shopcategoryname");
            return (Criteria) this;
        }

        public Criteria andShopcategorynameBetween(String value1, String value2) {
            addCriterion("shopCategoryName between", value1, value2, "shopcategoryname");
            return (Criteria) this;
        }

        public Criteria andShopcategorynameNotBetween(String value1, String value2) {
            addCriterion("shopCategoryName not between", value1, value2, "shopcategoryname");
            return (Criteria) this;
        }

        public Criteria andShopcategorydescIsNull() {
            addCriterion("shopCategoryDesc is null");
            return (Criteria) this;
        }

        public Criteria andShopcategorydescIsNotNull() {
            addCriterion("shopCategoryDesc is not null");
            return (Criteria) this;
        }

        public Criteria andShopcategorydescEqualTo(String value) {
            addCriterion("shopCategoryDesc =", value, "shopcategorydesc");
            return (Criteria) this;
        }

        public Criteria andShopcategorydescNotEqualTo(String value) {
            addCriterion("shopCategoryDesc <>", value, "shopcategorydesc");
            return (Criteria) this;
        }

        public Criteria andShopcategorydescGreaterThan(String value) {
            addCriterion("shopCategoryDesc >", value, "shopcategorydesc");
            return (Criteria) this;
        }

        public Criteria andShopcategorydescGreaterThanOrEqualTo(String value) {
            addCriterion("shopCategoryDesc >=", value, "shopcategorydesc");
            return (Criteria) this;
        }

        public Criteria andShopcategorydescLessThan(String value) {
            addCriterion("shopCategoryDesc <", value, "shopcategorydesc");
            return (Criteria) this;
        }

        public Criteria andShopcategorydescLessThanOrEqualTo(String value) {
            addCriterion("shopCategoryDesc <=", value, "shopcategorydesc");
            return (Criteria) this;
        }

        public Criteria andShopcategorydescLike(String value) {
            addCriterion("shopCategoryDesc like", value, "shopcategorydesc");
            return (Criteria) this;
        }

        public Criteria andShopcategorydescNotLike(String value) {
            addCriterion("shopCategoryDesc not like", value, "shopcategorydesc");
            return (Criteria) this;
        }

        public Criteria andShopcategorydescIn(List<String> values) {
            addCriterion("shopCategoryDesc in", values, "shopcategorydesc");
            return (Criteria) this;
        }

        public Criteria andShopcategorydescNotIn(List<String> values) {
            addCriterion("shopCategoryDesc not in", values, "shopcategorydesc");
            return (Criteria) this;
        }

        public Criteria andShopcategorydescBetween(String value1, String value2) {
            addCriterion("shopCategoryDesc between", value1, value2, "shopcategorydesc");
            return (Criteria) this;
        }

        public Criteria andShopcategorydescNotBetween(String value1, String value2) {
            addCriterion("shopCategoryDesc not between", value1, value2, "shopcategorydesc");
            return (Criteria) this;
        }

        public Criteria andShopcategoryimgIsNull() {
            addCriterion("shopCategoryImg is null");
            return (Criteria) this;
        }

        public Criteria andShopcategoryimgIsNotNull() {
            addCriterion("shopCategoryImg is not null");
            return (Criteria) this;
        }

        public Criteria andShopcategoryimgEqualTo(String value) {
            addCriterion("shopCategoryImg =", value, "shopcategoryimg");
            return (Criteria) this;
        }

        public Criteria andShopcategoryimgNotEqualTo(String value) {
            addCriterion("shopCategoryImg <>", value, "shopcategoryimg");
            return (Criteria) this;
        }

        public Criteria andShopcategoryimgGreaterThan(String value) {
            addCriterion("shopCategoryImg >", value, "shopcategoryimg");
            return (Criteria) this;
        }

        public Criteria andShopcategoryimgGreaterThanOrEqualTo(String value) {
            addCriterion("shopCategoryImg >=", value, "shopcategoryimg");
            return (Criteria) this;
        }

        public Criteria andShopcategoryimgLessThan(String value) {
            addCriterion("shopCategoryImg <", value, "shopcategoryimg");
            return (Criteria) this;
        }

        public Criteria andShopcategoryimgLessThanOrEqualTo(String value) {
            addCriterion("shopCategoryImg <=", value, "shopcategoryimg");
            return (Criteria) this;
        }

        public Criteria andShopcategoryimgLike(String value) {
            addCriterion("shopCategoryImg like", value, "shopcategoryimg");
            return (Criteria) this;
        }

        public Criteria andShopcategoryimgNotLike(String value) {
            addCriterion("shopCategoryImg not like", value, "shopcategoryimg");
            return (Criteria) this;
        }

        public Criteria andShopcategoryimgIn(List<String> values) {
            addCriterion("shopCategoryImg in", values, "shopcategoryimg");
            return (Criteria) this;
        }

        public Criteria andShopcategoryimgNotIn(List<String> values) {
            addCriterion("shopCategoryImg not in", values, "shopcategoryimg");
            return (Criteria) this;
        }

        public Criteria andShopcategoryimgBetween(String value1, String value2) {
            addCriterion("shopCategoryImg between", value1, value2, "shopcategoryimg");
            return (Criteria) this;
        }

        public Criteria andShopcategoryimgNotBetween(String value1, String value2) {
            addCriterion("shopCategoryImg not between", value1, value2, "shopcategoryimg");
            return (Criteria) this;
        }

        public Criteria andShopcategorycreatetimeIsNull() {
            addCriterion("shopCategoryCreateTime is null");
            return (Criteria) this;
        }

        public Criteria andShopcategorycreatetimeIsNotNull() {
            addCriterion("shopCategoryCreateTime is not null");
            return (Criteria) this;
        }

        public Criteria andShopcategorycreatetimeEqualTo(Date value) {
            addCriterion("shopCategoryCreateTime =", value, "shopcategorycreatetime");
            return (Criteria) this;
        }

        public Criteria andShopcategorycreatetimeNotEqualTo(Date value) {
            addCriterion("shopCategoryCreateTime <>", value, "shopcategorycreatetime");
            return (Criteria) this;
        }

        public Criteria andShopcategorycreatetimeGreaterThan(Date value) {
            addCriterion("shopCategoryCreateTime >", value, "shopcategorycreatetime");
            return (Criteria) this;
        }

        public Criteria andShopcategorycreatetimeGreaterThanOrEqualTo(Date value) {
            addCriterion("shopCategoryCreateTime >=", value, "shopcategorycreatetime");
            return (Criteria) this;
        }

        public Criteria andShopcategorycreatetimeLessThan(Date value) {
            addCriterion("shopCategoryCreateTime <", value, "shopcategorycreatetime");
            return (Criteria) this;
        }

        public Criteria andShopcategorycreatetimeLessThanOrEqualTo(Date value) {
            addCriterion("shopCategoryCreateTime <=", value, "shopcategorycreatetime");
            return (Criteria) this;
        }

        public Criteria andShopcategorycreatetimeIn(List<Date> values) {
            addCriterion("shopCategoryCreateTime in", values, "shopcategorycreatetime");
            return (Criteria) this;
        }

        public Criteria andShopcategorycreatetimeNotIn(List<Date> values) {
            addCriterion("shopCategoryCreateTime not in", values, "shopcategorycreatetime");
            return (Criteria) this;
        }

        public Criteria andShopcategorycreatetimeBetween(Date value1, Date value2) {
            addCriterion("shopCategoryCreateTime between", value1, value2, "shopcategorycreatetime");
            return (Criteria) this;
        }

        public Criteria andShopcategorycreatetimeNotBetween(Date value1, Date value2) {
            addCriterion("shopCategoryCreateTime not between", value1, value2, "shopcategorycreatetime");
            return (Criteria) this;
        }

        public Criteria andShopcategoryupdatetimeIsNull() {
            addCriterion("shopCategoryUpdateTime is null");
            return (Criteria) this;
        }

        public Criteria andShopcategoryupdatetimeIsNotNull() {
            addCriterion("shopCategoryUpdateTime is not null");
            return (Criteria) this;
        }

        public Criteria andShopcategoryupdatetimeEqualTo(Date value) {
            addCriterion("shopCategoryUpdateTime =", value, "shopcategoryupdatetime");
            return (Criteria) this;
        }

        public Criteria andShopcategoryupdatetimeNotEqualTo(Date value) {
            addCriterion("shopCategoryUpdateTime <>", value, "shopcategoryupdatetime");
            return (Criteria) this;
        }

        public Criteria andShopcategoryupdatetimeGreaterThan(Date value) {
            addCriterion("shopCategoryUpdateTime >", value, "shopcategoryupdatetime");
            return (Criteria) this;
        }

        public Criteria andShopcategoryupdatetimeGreaterThanOrEqualTo(Date value) {
            addCriterion("shopCategoryUpdateTime >=", value, "shopcategoryupdatetime");
            return (Criteria) this;
        }

        public Criteria andShopcategoryupdatetimeLessThan(Date value) {
            addCriterion("shopCategoryUpdateTime <", value, "shopcategoryupdatetime");
            return (Criteria) this;
        }

        public Criteria andShopcategoryupdatetimeLessThanOrEqualTo(Date value) {
            addCriterion("shopCategoryUpdateTime <=", value, "shopcategoryupdatetime");
            return (Criteria) this;
        }

        public Criteria andShopcategoryupdatetimeIn(List<Date> values) {
            addCriterion("shopCategoryUpdateTime in", values, "shopcategoryupdatetime");
            return (Criteria) this;
        }

        public Criteria andShopcategoryupdatetimeNotIn(List<Date> values) {
            addCriterion("shopCategoryUpdateTime not in", values, "shopcategoryupdatetime");
            return (Criteria) this;
        }

        public Criteria andShopcategoryupdatetimeBetween(Date value1, Date value2) {
            addCriterion("shopCategoryUpdateTime between", value1, value2, "shopcategoryupdatetime");
            return (Criteria) this;
        }

        public Criteria andShopcategoryupdatetimeNotBetween(Date value1, Date value2) {
            addCriterion("shopCategoryUpdateTime not between", value1, value2, "shopcategoryupdatetime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table shopcategory
     *
     * @mbg.generated do_not_delete_during_merge Tue May 14 10:43:09 CST 2019
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table shopcategory
     *
     * @mbg.generated Tue May 14 10:43:09 CST 2019
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}