package club.bagedate.o2o.entity;

import java.util.Date;

public class ShopCategory {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shopcategory.shopCategoryId
     *
     * @mbg.generated Tue May 14 10:43:09 CST 2019
     */
    private Integer shopcategoryid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shopcategory.shopCategoryPriority
     *
     * @mbg.generated Tue May 14 10:43:09 CST 2019
     */
    private Integer shopcategorypriority;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shopcategory.shopCategoryParentId
     *
     * @mbg.generated Tue May 14 10:43:09 CST 2019
     */
    private Integer shopcategoryparentid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shopcategory.shopCategoryName
     *
     * @mbg.generated Tue May 14 10:43:09 CST 2019
     */
    private String shopcategoryname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shopcategory.shopCategoryDesc
     *
     * @mbg.generated Tue May 14 10:43:09 CST 2019
     */
    private String shopcategorydesc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shopcategory.shopCategoryImg
     *
     * @mbg.generated Tue May 14 10:43:09 CST 2019
     */
    private String shopcategoryimg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shopcategory.shopCategoryCreateTime
     *
     * @mbg.generated Tue May 14 10:43:09 CST 2019
     */
    private Date shopcategorycreatetime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shopcategory.shopCategoryUpdateTime
     *
     * @mbg.generated Tue May 14 10:43:09 CST 2019
     */
    private Date shopcategoryupdatetime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shopcategory.shopCategoryId
     *
     * @return the value of shopcategory.shopCategoryId
     *
     * @mbg.generated Tue May 14 10:43:09 CST 2019
     */
    public Integer getShopcategoryid() {
        return shopcategoryid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shopcategory.shopCategoryId
     *
     * @param shopcategoryid the value for shopcategory.shopCategoryId
     *
     * @mbg.generated Tue May 14 10:43:09 CST 2019
     */
    public void setShopcategoryid(Integer shopcategoryid) {
        this.shopcategoryid = shopcategoryid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shopcategory.shopCategoryPriority
     *
     * @return the value of shopcategory.shopCategoryPriority
     *
     * @mbg.generated Tue May 14 10:43:09 CST 2019
     */
    public Integer getShopcategorypriority() {
        return shopcategorypriority;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shopcategory.shopCategoryPriority
     *
     * @param shopcategorypriority the value for shopcategory.shopCategoryPriority
     *
     * @mbg.generated Tue May 14 10:43:09 CST 2019
     */
    public void setShopcategorypriority(Integer shopcategorypriority) {
        this.shopcategorypriority = shopcategorypriority;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shopcategory.shopCategoryParentId
     *
     * @return the value of shopcategory.shopCategoryParentId
     *
     * @mbg.generated Tue May 14 10:43:09 CST 2019
     */
    public Integer getShopcategoryparentid() {
        return shopcategoryparentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shopcategory.shopCategoryParentId
     *
     * @param shopcategoryparentid the value for shopcategory.shopCategoryParentId
     *
     * @mbg.generated Tue May 14 10:43:09 CST 2019
     */
    public void setShopcategoryparentid(Integer shopcategoryparentid) {
        this.shopcategoryparentid = shopcategoryparentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shopcategory.shopCategoryName
     *
     * @return the value of shopcategory.shopCategoryName
     *
     * @mbg.generated Tue May 14 10:43:09 CST 2019
     */
    public String getShopcategoryname() {
        return shopcategoryname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shopcategory.shopCategoryName
     *
     * @param shopcategoryname the value for shopcategory.shopCategoryName
     *
     * @mbg.generated Tue May 14 10:43:09 CST 2019
     */
    public void setShopcategoryname(String shopcategoryname) {
        this.shopcategoryname = shopcategoryname == null ? null : shopcategoryname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shopcategory.shopCategoryDesc
     *
     * @return the value of shopcategory.shopCategoryDesc
     *
     * @mbg.generated Tue May 14 10:43:09 CST 2019
     */
    public String getShopcategorydesc() {
        return shopcategorydesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shopcategory.shopCategoryDesc
     *
     * @param shopcategorydesc the value for shopcategory.shopCategoryDesc
     *
     * @mbg.generated Tue May 14 10:43:09 CST 2019
     */
    public void setShopcategorydesc(String shopcategorydesc) {
        this.shopcategorydesc = shopcategorydesc == null ? null : shopcategorydesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shopcategory.shopCategoryImg
     *
     * @return the value of shopcategory.shopCategoryImg
     *
     * @mbg.generated Tue May 14 10:43:09 CST 2019
     */
    public String getShopcategoryimg() {
        return shopcategoryimg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shopcategory.shopCategoryImg
     *
     * @param shopcategoryimg the value for shopcategory.shopCategoryImg
     *
     * @mbg.generated Tue May 14 10:43:09 CST 2019
     */
    public void setShopcategoryimg(String shopcategoryimg) {
        this.shopcategoryimg = shopcategoryimg == null ? null : shopcategoryimg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shopcategory.shopCategoryCreateTime
     *
     * @return the value of shopcategory.shopCategoryCreateTime
     *
     * @mbg.generated Tue May 14 10:43:09 CST 2019
     */
    public Date getShopcategorycreatetime() {
        return shopcategorycreatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shopcategory.shopCategoryCreateTime
     *
     * @param shopcategorycreatetime the value for shopcategory.shopCategoryCreateTime
     *
     * @mbg.generated Tue May 14 10:43:09 CST 2019
     */
    public void setShopcategorycreatetime(Date shopcategorycreatetime) {
        this.shopcategorycreatetime = shopcategorycreatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shopcategory.shopCategoryUpdateTime
     *
     * @return the value of shopcategory.shopCategoryUpdateTime
     *
     * @mbg.generated Tue May 14 10:43:09 CST 2019
     */
    public Date getShopcategoryupdatetime() {
        return shopcategoryupdatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shopcategory.shopCategoryUpdateTime
     *
     * @param shopcategoryupdatetime the value for shopcategory.shopCategoryUpdateTime
     *
     * @mbg.generated Tue May 14 10:43:09 CST 2019
     */
    public void setShopcategoryupdatetime(Date shopcategoryupdatetime) {
        this.shopcategoryupdatetime = shopcategoryupdatetime;
    }
}