package club.bagedate.o2o.entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class ShopExample {
    protected Integer leftLimit;
    protected Integer limitSize;

    public Integer getLeftLimit() {
        return leftLimit;
    }

    public void setLeftLimit(Integer leftLimit) {
        this.leftLimit = leftLimit;
    }

    public Integer getLimitSize() {
        return limitSize;
    }

    public void setLimitSize(Integer limitSize) {
        this.limitSize = limitSize;
    }

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table shop
     *
     * @mbg.generated Tue May 14 10:43:09 CST 2019
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table shop
     *
     * @mbg.generated Tue May 14 10:43:09 CST 2019
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table shop
     *
     * @mbg.generated Tue May 14 10:43:09 CST 2019
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop
     *
     * @mbg.generated Tue May 14 10:43:09 CST 2019
     */
    public ShopExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop
     *
     * @mbg.generated Tue May 14 10:43:09 CST 2019
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop
     *
     * @mbg.generated Tue May 14 10:43:09 CST 2019
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop
     *
     * @mbg.generated Tue May 14 10:43:09 CST 2019
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop
     *
     * @mbg.generated Tue May 14 10:43:09 CST 2019
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop
     *
     * @mbg.generated Tue May 14 10:43:09 CST 2019
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop
     *
     * @mbg.generated Tue May 14 10:43:09 CST 2019
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop
     *
     * @mbg.generated Tue May 14 10:43:09 CST 2019
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop
     *
     * @mbg.generated Tue May 14 10:43:09 CST 2019
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop
     *
     * @mbg.generated Tue May 14 10:43:09 CST 2019
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop
     *
     * @mbg.generated Tue May 14 10:43:09 CST 2019
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table shop
     *
     * @mbg.generated Tue May 14 10:43:09 CST 2019
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andShopidIsNull() {
            addCriterion("shopId is null");
            return (Criteria) this;
        }

        public Criteria andShopidIsNotNull() {
            addCriterion("shopId is not null");
            return (Criteria) this;
        }

        public Criteria andShopidEqualTo(Integer value) {
            addCriterion("shopId =", value, "shopid");
            return (Criteria) this;
        }

        public Criteria andShopidNotEqualTo(Integer value) {
            addCriterion("shopId <>", value, "shopid");
            return (Criteria) this;
        }

        public Criteria andShopidGreaterThan(Integer value) {
            addCriterion("shopId >", value, "shopid");
            return (Criteria) this;
        }

        public Criteria andShopidGreaterThanOrEqualTo(Integer value) {
            addCriterion("shopId >=", value, "shopid");
            return (Criteria) this;
        }

        public Criteria andShopidLessThan(Integer value) {
            addCriterion("shopId <", value, "shopid");
            return (Criteria) this;
        }

        public Criteria andShopidLessThanOrEqualTo(Integer value) {
            addCriterion("shopId <=", value, "shopid");
            return (Criteria) this;
        }

        public Criteria andShopidIn(List<Integer> values) {
            addCriterion("shopId in", values, "shopid");
            return (Criteria) this;
        }

        public Criteria andShopidNotIn(List<Integer> values) {
            addCriterion("shopId not in", values, "shopid");
            return (Criteria) this;
        }

        public Criteria andShopidBetween(Integer value1, Integer value2) {
            addCriterion("shopId between", value1, value2, "shopid");
            return (Criteria) this;
        }

        public Criteria andShopidNotBetween(Integer value1, Integer value2) {
            addCriterion("shopId not between", value1, value2, "shopid");
            return (Criteria) this;
        }

        public Criteria andShoppriorityIsNull() {
            addCriterion("shopPriority is null");
            return (Criteria) this;
        }

        public Criteria andShoppriorityIsNotNull() {
            addCriterion("shopPriority is not null");
            return (Criteria) this;
        }

        public Criteria andShoppriorityEqualTo(Integer value) {
            addCriterion("shopPriority =", value, "shoppriority");
            return (Criteria) this;
        }

        public Criteria andShoppriorityNotEqualTo(Integer value) {
            addCriterion("shopPriority <>", value, "shoppriority");
            return (Criteria) this;
        }

        public Criteria andShoppriorityGreaterThan(Integer value) {
            addCriterion("shopPriority >", value, "shoppriority");
            return (Criteria) this;
        }

        public Criteria andShoppriorityGreaterThanOrEqualTo(Integer value) {
            addCriterion("shopPriority >=", value, "shoppriority");
            return (Criteria) this;
        }

        public Criteria andShoppriorityLessThan(Integer value) {
            addCriterion("shopPriority <", value, "shoppriority");
            return (Criteria) this;
        }

        public Criteria andShoppriorityLessThanOrEqualTo(Integer value) {
            addCriterion("shopPriority <=", value, "shoppriority");
            return (Criteria) this;
        }

        public Criteria andShoppriorityIn(List<Integer> values) {
            addCriterion("shopPriority in", values, "shoppriority");
            return (Criteria) this;
        }

        public Criteria andShoppriorityNotIn(List<Integer> values) {
            addCriterion("shopPriority not in", values, "shoppriority");
            return (Criteria) this;
        }

        public Criteria andShoppriorityBetween(Integer value1, Integer value2) {
            addCriterion("shopPriority between", value1, value2, "shoppriority");
            return (Criteria) this;
        }

        public Criteria andShoppriorityNotBetween(Integer value1, Integer value2) {
            addCriterion("shopPriority not between", value1, value2, "shoppriority");
            return (Criteria) this;
        }

        public Criteria andShopimgIsNull() {
            addCriterion("shopImg is null");
            return (Criteria) this;
        }

        public Criteria andShopimgIsNotNull() {
            addCriterion("shopImg is not null");
            return (Criteria) this;
        }

        public Criteria andShopimgEqualTo(String value) {
            addCriterion("shopImg =", value, "shopimg");
            return (Criteria) this;
        }

        public Criteria andShopimgNotEqualTo(String value) {
            addCriterion("shopImg <>", value, "shopimg");
            return (Criteria) this;
        }

        public Criteria andShopimgGreaterThan(String value) {
            addCriterion("shopImg >", value, "shopimg");
            return (Criteria) this;
        }

        public Criteria andShopimgGreaterThanOrEqualTo(String value) {
            addCriterion("shopImg >=", value, "shopimg");
            return (Criteria) this;
        }

        public Criteria andShopimgLessThan(String value) {
            addCriterion("shopImg <", value, "shopimg");
            return (Criteria) this;
        }

        public Criteria andShopimgLessThanOrEqualTo(String value) {
            addCriterion("shopImg <=", value, "shopimg");
            return (Criteria) this;
        }

        public Criteria andShopimgLike(String value) {
            addCriterion("shopImg like", value, "shopimg");
            return (Criteria) this;
        }

        public Criteria andShopimgNotLike(String value) {
            addCriterion("shopImg not like", value, "shopimg");
            return (Criteria) this;
        }

        public Criteria andShopimgIn(List<String> values) {
            addCriterion("shopImg in", values, "shopimg");
            return (Criteria) this;
        }

        public Criteria andShopimgNotIn(List<String> values) {
            addCriterion("shopImg not in", values, "shopimg");
            return (Criteria) this;
        }

        public Criteria andShopimgBetween(String value1, String value2) {
            addCriterion("shopImg between", value1, value2, "shopimg");
            return (Criteria) this;
        }

        public Criteria andShopimgNotBetween(String value1, String value2) {
            addCriterion("shopImg not between", value1, value2, "shopimg");
            return (Criteria) this;
        }

        public Criteria andShopnameIsNull() {
            addCriterion("shopName is null");
            return (Criteria) this;
        }

        public Criteria andShopnameIsNotNull() {
            addCriterion("shopName is not null");
            return (Criteria) this;
        }

        public Criteria andShopnameEqualTo(String value) {
            addCriterion("shopName =", value, "shopname");
            return (Criteria) this;
        }

        public Criteria andShopnameNotEqualTo(String value) {
            addCriterion("shopName <>", value, "shopname");
            return (Criteria) this;
        }

        public Criteria andShopnameGreaterThan(String value) {
            addCriterion("shopName >", value, "shopname");
            return (Criteria) this;
        }

        public Criteria andShopnameGreaterThanOrEqualTo(String value) {
            addCriterion("shopName >=", value, "shopname");
            return (Criteria) this;
        }

        public Criteria andShopnameLessThan(String value) {
            addCriterion("shopName <", value, "shopname");
            return (Criteria) this;
        }

        public Criteria andShopnameLessThanOrEqualTo(String value) {
            addCriterion("shopName <=", value, "shopname");
            return (Criteria) this;
        }

        public Criteria andShopnameLike(String value) {
            addCriterion("shopName like", value, "shopname");
            return (Criteria) this;
        }

        public Criteria andShopnameNotLike(String value) {
            addCriterion("shopName not like", value, "shopname");
            return (Criteria) this;
        }

        public Criteria andShopnameIn(List<String> values) {
            addCriterion("shopName in", values, "shopname");
            return (Criteria) this;
        }

        public Criteria andShopnameNotIn(List<String> values) {
            addCriterion("shopName not in", values, "shopname");
            return (Criteria) this;
        }

        public Criteria andShopnameBetween(String value1, String value2) {
            addCriterion("shopName between", value1, value2, "shopname");
            return (Criteria) this;
        }

        public Criteria andShopnameNotBetween(String value1, String value2) {
            addCriterion("shopName not between", value1, value2, "shopname");
            return (Criteria) this;
        }

        public Criteria andShopdescIsNull() {
            addCriterion("shopDesc is null");
            return (Criteria) this;
        }

        public Criteria andShopdescIsNotNull() {
            addCriterion("shopDesc is not null");
            return (Criteria) this;
        }

        public Criteria andShopdescEqualTo(String value) {
            addCriterion("shopDesc =", value, "shopdesc");
            return (Criteria) this;
        }

        public Criteria andShopdescNotEqualTo(String value) {
            addCriterion("shopDesc <>", value, "shopdesc");
            return (Criteria) this;
        }

        public Criteria andShopdescGreaterThan(String value) {
            addCriterion("shopDesc >", value, "shopdesc");
            return (Criteria) this;
        }

        public Criteria andShopdescGreaterThanOrEqualTo(String value) {
            addCriterion("shopDesc >=", value, "shopdesc");
            return (Criteria) this;
        }

        public Criteria andShopdescLessThan(String value) {
            addCriterion("shopDesc <", value, "shopdesc");
            return (Criteria) this;
        }

        public Criteria andShopdescLessThanOrEqualTo(String value) {
            addCriterion("shopDesc <=", value, "shopdesc");
            return (Criteria) this;
        }

        public Criteria andShopdescLike(String value) {
            addCriterion("shopDesc like", value, "shopdesc");
            return (Criteria) this;
        }

        public Criteria andShopdescNotLike(String value) {
            addCriterion("shopDesc not like", value, "shopdesc");
            return (Criteria) this;
        }

        public Criteria andShopdescIn(List<String> values) {
            addCriterion("shopDesc in", values, "shopdesc");
            return (Criteria) this;
        }

        public Criteria andShopdescNotIn(List<String> values) {
            addCriterion("shopDesc not in", values, "shopdesc");
            return (Criteria) this;
        }

        public Criteria andShopdescBetween(String value1, String value2) {
            addCriterion("shopDesc between", value1, value2, "shopdesc");
            return (Criteria) this;
        }

        public Criteria andShopdescNotBetween(String value1, String value2) {
            addCriterion("shopDesc not between", value1, value2, "shopdesc");
            return (Criteria) this;
        }

        public Criteria andShopphonenumberIsNull() {
            addCriterion("shopPhoneNumber is null");
            return (Criteria) this;
        }

        public Criteria andShopphonenumberIsNotNull() {
            addCriterion("shopPhoneNumber is not null");
            return (Criteria) this;
        }

        public Criteria andShopphonenumberEqualTo(String value) {
            addCriterion("shopPhoneNumber =", value, "shopphonenumber");
            return (Criteria) this;
        }

        public Criteria andShopphonenumberNotEqualTo(String value) {
            addCriterion("shopPhoneNumber <>", value, "shopphonenumber");
            return (Criteria) this;
        }

        public Criteria andShopphonenumberGreaterThan(String value) {
            addCriterion("shopPhoneNumber >", value, "shopphonenumber");
            return (Criteria) this;
        }

        public Criteria andShopphonenumberGreaterThanOrEqualTo(String value) {
            addCriterion("shopPhoneNumber >=", value, "shopphonenumber");
            return (Criteria) this;
        }

        public Criteria andShopphonenumberLessThan(String value) {
            addCriterion("shopPhoneNumber <", value, "shopphonenumber");
            return (Criteria) this;
        }

        public Criteria andShopphonenumberLessThanOrEqualTo(String value) {
            addCriterion("shopPhoneNumber <=", value, "shopphonenumber");
            return (Criteria) this;
        }

        public Criteria andShopphonenumberLike(String value) {
            addCriterion("shopPhoneNumber like", value, "shopphonenumber");
            return (Criteria) this;
        }

        public Criteria andShopphonenumberNotLike(String value) {
            addCriterion("shopPhoneNumber not like", value, "shopphonenumber");
            return (Criteria) this;
        }

        public Criteria andShopphonenumberIn(List<String> values) {
            addCriterion("shopPhoneNumber in", values, "shopphonenumber");
            return (Criteria) this;
        }

        public Criteria andShopphonenumberNotIn(List<String> values) {
            addCriterion("shopPhoneNumber not in", values, "shopphonenumber");
            return (Criteria) this;
        }

        public Criteria andShopphonenumberBetween(String value1, String value2) {
            addCriterion("shopPhoneNumber between", value1, value2, "shopphonenumber");
            return (Criteria) this;
        }

        public Criteria andShopphonenumberNotBetween(String value1, String value2) {
            addCriterion("shopPhoneNumber not between", value1, value2, "shopphonenumber");
            return (Criteria) this;
        }

        public Criteria andShopplaceIsNull() {
            addCriterion("shopPlace is null");
            return (Criteria) this;
        }

        public Criteria andShopplaceIsNotNull() {
            addCriterion("shopPlace is not null");
            return (Criteria) this;
        }

        public Criteria andShopplaceEqualTo(String value) {
            addCriterion("shopPlace =", value, "shopplace");
            return (Criteria) this;
        }

        public Criteria andShopplaceNotEqualTo(String value) {
            addCriterion("shopPlace <>", value, "shopplace");
            return (Criteria) this;
        }

        public Criteria andShopplaceGreaterThan(String value) {
            addCriterion("shopPlace >", value, "shopplace");
            return (Criteria) this;
        }

        public Criteria andShopplaceGreaterThanOrEqualTo(String value) {
            addCriterion("shopPlace >=", value, "shopplace");
            return (Criteria) this;
        }

        public Criteria andShopplaceLessThan(String value) {
            addCriterion("shopPlace <", value, "shopplace");
            return (Criteria) this;
        }

        public Criteria andShopplaceLessThanOrEqualTo(String value) {
            addCriterion("shopPlace <=", value, "shopplace");
            return (Criteria) this;
        }

        public Criteria andShopplaceLike(String value) {
            addCriterion("shopPlace like", value, "shopplace");
            return (Criteria) this;
        }

        public Criteria andShopplaceNotLike(String value) {
            addCriterion("shopPlace not like", value, "shopplace");
            return (Criteria) this;
        }

        public Criteria andShopplaceIn(List<String> values) {
            addCriterion("shopPlace in", values, "shopplace");
            return (Criteria) this;
        }

        public Criteria andShopplaceNotIn(List<String> values) {
            addCriterion("shopPlace not in", values, "shopplace");
            return (Criteria) this;
        }

        public Criteria andShopplaceBetween(String value1, String value2) {
            addCriterion("shopPlace between", value1, value2, "shopplace");
            return (Criteria) this;
        }

        public Criteria andShopplaceNotBetween(String value1, String value2) {
            addCriterion("shopPlace not between", value1, value2, "shopplace");
            return (Criteria) this;
        }

        public Criteria andPlaceidIsNull() {
            addCriterion("placeId is null");
            return (Criteria) this;
        }

        public Criteria andPlaceidIsNotNull() {
            addCriterion("placeId is not null");
            return (Criteria) this;
        }

        public Criteria andPlaceidEqualTo(Integer value) {
            addCriterion("placeId =", value, "placeid");
            return (Criteria) this;
        }

        public Criteria andPlaceidNotEqualTo(Integer value) {
            addCriterion("placeId <>", value, "placeid");
            return (Criteria) this;
        }

        public Criteria andPlaceidGreaterThan(Integer value) {
            addCriterion("placeId >", value, "placeid");
            return (Criteria) this;
        }

        public Criteria andPlaceidGreaterThanOrEqualTo(Integer value) {
            addCriterion("placeId >=", value, "placeid");
            return (Criteria) this;
        }

        public Criteria andPlaceidLessThan(Integer value) {
            addCriterion("placeId <", value, "placeid");
            return (Criteria) this;
        }

        public Criteria andPlaceidLessThanOrEqualTo(Integer value) {
            addCriterion("placeId <=", value, "placeid");
            return (Criteria) this;
        }

        public Criteria andPlaceidIn(List<Integer> values) {
            addCriterion("placeId in", values, "placeid");
            return (Criteria) this;
        }

        public Criteria andPlaceidNotIn(List<Integer> values) {
            addCriterion("placeId not in", values, "placeid");
            return (Criteria) this;
        }

        public Criteria andPlaceidBetween(Integer value1, Integer value2) {
            addCriterion("placeId between", value1, value2, "placeid");
            return (Criteria) this;
        }

        public Criteria andPlaceidNotBetween(Integer value1, Integer value2) {
            addCriterion("placeId not between", value1, value2, "placeid");
            return (Criteria) this;
        }

        public Criteria andShopcategoryidIsNull() {
            addCriterion("shopCategoryId is null");
            return (Criteria) this;
        }

        public Criteria andShopcategoryidIsNotNull() {
            addCriterion("shopCategoryId is not null");
            return (Criteria) this;
        }

        public Criteria andShopcategoryidEqualTo(Integer value) {
            addCriterion("shopCategoryId =", value, "shopcategoryid");
            return (Criteria) this;
        }

        public Criteria andShopcategoryidNotEqualTo(Integer value) {
            addCriterion("shopCategoryId <>", value, "shopcategoryid");
            return (Criteria) this;
        }

        public Criteria andShopcategoryidGreaterThan(Integer value) {
            addCriterion("shopCategoryId >", value, "shopcategoryid");
            return (Criteria) this;
        }

        public Criteria andShopcategoryidGreaterThanOrEqualTo(Integer value) {
            addCriterion("shopCategoryId >=", value, "shopcategoryid");
            return (Criteria) this;
        }

        public Criteria andShopcategoryidLessThan(Integer value) {
            addCriterion("shopCategoryId <", value, "shopcategoryid");
            return (Criteria) this;
        }

        public Criteria andShopcategoryidLessThanOrEqualTo(Integer value) {
            addCriterion("shopCategoryId <=", value, "shopcategoryid");
            return (Criteria) this;
        }

        public Criteria andShopcategoryidIn(List<Integer> values) {
            addCriterion("shopCategoryId in", values, "shopcategoryid");
            return (Criteria) this;
        }

        public Criteria andShopcategoryidNotIn(List<Integer> values) {
            addCriterion("shopCategoryId not in", values, "shopcategoryid");
            return (Criteria) this;
        }

        public Criteria andShopcategoryidBetween(Integer value1, Integer value2) {
            addCriterion("shopCategoryId between", value1, value2, "shopcategoryid");
            return (Criteria) this;
        }

        public Criteria andShopcategoryidNotBetween(Integer value1, Integer value2) {
            addCriterion("shopCategoryId not between", value1, value2, "shopcategoryid");
            return (Criteria) this;
        }

        public Criteria andUseridIsNull() {
            addCriterion("userId is null");
            return (Criteria) this;
        }

        public Criteria andUseridIsNotNull() {
            addCriterion("userId is not null");
            return (Criteria) this;
        }

        public Criteria andUseridEqualTo(Integer value) {
            addCriterion("userId =", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridNotEqualTo(Integer value) {
            addCriterion("userId <>", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridGreaterThan(Integer value) {
            addCriterion("userId >", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridGreaterThanOrEqualTo(Integer value) {
            addCriterion("userId >=", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridLessThan(Integer value) {
            addCriterion("userId <", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridLessThanOrEqualTo(Integer value) {
            addCriterion("userId <=", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridIn(List<Integer> values) {
            addCriterion("userId in", values, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridNotIn(List<Integer> values) {
            addCriterion("userId not in", values, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridBetween(Integer value1, Integer value2) {
            addCriterion("userId between", value1, value2, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridNotBetween(Integer value1, Integer value2) {
            addCriterion("userId not between", value1, value2, "userid");
            return (Criteria) this;
        }

        public Criteria andShopstatusIsNull() {
            addCriterion("shopStatus is null");
            return (Criteria) this;
        }

        public Criteria andShopstatusIsNotNull() {
            addCriterion("shopStatus is not null");
            return (Criteria) this;
        }

        public Criteria andShopstatusEqualTo(Integer value) {
            addCriterion("shopStatus =", value, "shopstatus");
            return (Criteria) this;
        }

        public Criteria andShopstatusNotEqualTo(Integer value) {
            addCriterion("shopStatus <>", value, "shopstatus");
            return (Criteria) this;
        }

        public Criteria andShopstatusGreaterThan(Integer value) {
            addCriterion("shopStatus >", value, "shopstatus");
            return (Criteria) this;
        }

        public Criteria andShopstatusGreaterThanOrEqualTo(Integer value) {
            addCriterion("shopStatus >=", value, "shopstatus");
            return (Criteria) this;
        }

        public Criteria andShopstatusLessThan(Integer value) {
            addCriterion("shopStatus <", value, "shopstatus");
            return (Criteria) this;
        }

        public Criteria andShopstatusLessThanOrEqualTo(Integer value) {
            addCriterion("shopStatus <=", value, "shopstatus");
            return (Criteria) this;
        }

        public Criteria andShopstatusIn(List<Integer> values) {
            addCriterion("shopStatus in", values, "shopstatus");
            return (Criteria) this;
        }

        public Criteria andShopstatusNotIn(List<Integer> values) {
            addCriterion("shopStatus not in", values, "shopstatus");
            return (Criteria) this;
        }

        public Criteria andShopstatusBetween(Integer value1, Integer value2) {
            addCriterion("shopStatus between", value1, value2, "shopstatus");
            return (Criteria) this;
        }

        public Criteria andShopstatusNotBetween(Integer value1, Integer value2) {
            addCriterion("shopStatus not between", value1, value2, "shopstatus");
            return (Criteria) this;
        }

        public Criteria andShopcreatetimeIsNull() {
            addCriterion("shopCreateTime is null");
            return (Criteria) this;
        }

        public Criteria andShopcreatetimeIsNotNull() {
            addCriterion("shopCreateTime is not null");
            return (Criteria) this;
        }

        public Criteria andShopcreatetimeEqualTo(Date value) {
            addCriterion("shopCreateTime =", value, "shopcreatetime");
            return (Criteria) this;
        }

        public Criteria andShopcreatetimeNotEqualTo(Date value) {
            addCriterion("shopCreateTime <>", value, "shopcreatetime");
            return (Criteria) this;
        }

        public Criteria andShopcreatetimeGreaterThan(Date value) {
            addCriterion("shopCreateTime >", value, "shopcreatetime");
            return (Criteria) this;
        }

        public Criteria andShopcreatetimeGreaterThanOrEqualTo(Date value) {
            addCriterion("shopCreateTime >=", value, "shopcreatetime");
            return (Criteria) this;
        }

        public Criteria andShopcreatetimeLessThan(Date value) {
            addCriterion("shopCreateTime <", value, "shopcreatetime");
            return (Criteria) this;
        }

        public Criteria andShopcreatetimeLessThanOrEqualTo(Date value) {
            addCriterion("shopCreateTime <=", value, "shopcreatetime");
            return (Criteria) this;
        }

        public Criteria andShopcreatetimeIn(List<Date> values) {
            addCriterion("shopCreateTime in", values, "shopcreatetime");
            return (Criteria) this;
        }

        public Criteria andShopcreatetimeNotIn(List<Date> values) {
            addCriterion("shopCreateTime not in", values, "shopcreatetime");
            return (Criteria) this;
        }

        public Criteria andShopcreatetimeBetween(Date value1, Date value2) {
            addCriterion("shopCreateTime between", value1, value2, "shopcreatetime");
            return (Criteria) this;
        }

        public Criteria andShopcreatetimeNotBetween(Date value1, Date value2) {
            addCriterion("shopCreateTime not between", value1, value2, "shopcreatetime");
            return (Criteria) this;
        }

        public Criteria andShopupdatetimeIsNull() {
            addCriterion("shopUpdateTime is null");
            return (Criteria) this;
        }

        public Criteria andShopupdatetimeIsNotNull() {
            addCriterion("shopUpdateTime is not null");
            return (Criteria) this;
        }

        public Criteria andShopupdatetimeEqualTo(Date value) {
            addCriterion("shopUpdateTime =", value, "shopupdatetime");
            return (Criteria) this;
        }

        public Criteria andShopupdatetimeNotEqualTo(Date value) {
            addCriterion("shopUpdateTime <>", value, "shopupdatetime");
            return (Criteria) this;
        }

        public Criteria andShopupdatetimeGreaterThan(Date value) {
            addCriterion("shopUpdateTime >", value, "shopupdatetime");
            return (Criteria) this;
        }

        public Criteria andShopupdatetimeGreaterThanOrEqualTo(Date value) {
            addCriterion("shopUpdateTime >=", value, "shopupdatetime");
            return (Criteria) this;
        }

        public Criteria andShopupdatetimeLessThan(Date value) {
            addCriterion("shopUpdateTime <", value, "shopupdatetime");
            return (Criteria) this;
        }

        public Criteria andShopupdatetimeLessThanOrEqualTo(Date value) {
            addCriterion("shopUpdateTime <=", value, "shopupdatetime");
            return (Criteria) this;
        }

        public Criteria andShopupdatetimeIn(List<Date> values) {
            addCriterion("shopUpdateTime in", values, "shopupdatetime");
            return (Criteria) this;
        }

        public Criteria andShopupdatetimeNotIn(List<Date> values) {
            addCriterion("shopUpdateTime not in", values, "shopupdatetime");
            return (Criteria) this;
        }

        public Criteria andShopupdatetimeBetween(Date value1, Date value2) {
            addCriterion("shopUpdateTime between", value1, value2, "shopupdatetime");
            return (Criteria) this;
        }

        public Criteria andShopupdatetimeNotBetween(Date value1, Date value2) {
            addCriterion("shopUpdateTime not between", value1, value2, "shopupdatetime");
            return (Criteria) this;
        }

        public Criteria andShopadviceIsNull() {
            addCriterion("shopAdvice is null");
            return (Criteria) this;
        }

        public Criteria andShopadviceIsNotNull() {
            addCriterion("shopAdvice is not null");
            return (Criteria) this;
        }

        public Criteria andShopadviceEqualTo(String value) {
            addCriterion("shopAdvice =", value, "shopadvice");
            return (Criteria) this;
        }

        public Criteria andShopadviceNotEqualTo(String value) {
            addCriterion("shopAdvice <>", value, "shopadvice");
            return (Criteria) this;
        }

        public Criteria andShopadviceGreaterThan(String value) {
            addCriterion("shopAdvice >", value, "shopadvice");
            return (Criteria) this;
        }

        public Criteria andShopadviceGreaterThanOrEqualTo(String value) {
            addCriterion("shopAdvice >=", value, "shopadvice");
            return (Criteria) this;
        }

        public Criteria andShopadviceLessThan(String value) {
            addCriterion("shopAdvice <", value, "shopadvice");
            return (Criteria) this;
        }

        public Criteria andShopadviceLessThanOrEqualTo(String value) {
            addCriterion("shopAdvice <=", value, "shopadvice");
            return (Criteria) this;
        }

        public Criteria andShopadviceLike(String value) {
            addCriterion("shopAdvice like", value, "shopadvice");
            return (Criteria) this;
        }

        public Criteria andShopadviceNotLike(String value) {
            addCriterion("shopAdvice not like", value, "shopadvice");
            return (Criteria) this;
        }

        public Criteria andShopadviceIn(List<String> values) {
            addCriterion("shopAdvice in", values, "shopadvice");
            return (Criteria) this;
        }

        public Criteria andShopadviceNotIn(List<String> values) {
            addCriterion("shopAdvice not in", values, "shopadvice");
            return (Criteria) this;
        }

        public Criteria andShopadviceBetween(String value1, String value2) {
            addCriterion("shopAdvice between", value1, value2, "shopadvice");
            return (Criteria) this;
        }

        public Criteria andShopadviceNotBetween(String value1, String value2) {
            addCriterion("shopAdvice not between", value1, value2, "shopadvice");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table shop
     *
     * @mbg.generated do_not_delete_during_merge Tue May 14 10:43:09 CST 2019
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table shop
     *
     * @mbg.generated Tue May 14 10:43:09 CST 2019
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}