package club.bagedate.o2o.entity;

import java.util.Date;

public class Shop {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop.shopId
     *
     * @mbg.generated Tue May 14 10:43:09 CST 2019
     */
    private Integer shopid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop.shopPriority
     *
     * @mbg.generated Tue May 14 10:43:09 CST 2019
     */
    private Integer shoppriority;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop.shopImg
     *
     * @mbg.generated Tue May 14 10:43:09 CST 2019
     */
    private String shopimg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop.shopName
     *
     * @mbg.generated Tue May 14 10:43:09 CST 2019
     */
    private String shopname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop.shopDesc
     *
     * @mbg.generated Tue May 14 10:43:09 CST 2019
     */
    private String shopdesc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop.shopPhoneNumber
     *
     * @mbg.generated Tue May 14 10:43:09 CST 2019
     */
    private String shopphonenumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop.shopPlace
     *
     * @mbg.generated Tue May 14 10:43:09 CST 2019
     */
    private String shopplace;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop.placeId
     *
     * @mbg.generated Tue May 14 10:43:09 CST 2019
     */
    private Integer placeid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop.shopCategoryId
     *
     * @mbg.generated Tue May 14 10:43:09 CST 2019
     */
    private Integer shopcategoryid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop.userId
     *
     * @mbg.generated Tue May 14 10:43:09 CST 2019
     */
    private Integer userid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop.shopStatus
     *
     * @mbg.generated Tue May 14 10:43:09 CST 2019
     */
    private Integer shopstatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop.shopCreateTime
     *
     * @mbg.generated Tue May 14 10:43:09 CST 2019
     */
    private Date shopcreatetime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop.shopUpdateTime
     *
     * @mbg.generated Tue May 14 10:43:09 CST 2019
     */
    private Date shopupdatetime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop.shopAdvice
     *
     * @mbg.generated Tue May 14 10:43:09 CST 2019
     */
    private String shopadvice;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop.shopId
     *
     * @return the value of shop.shopId
     *
     * @mbg.generated Tue May 14 10:43:09 CST 2019
     */
    public Integer getShopid() {
        return shopid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop.shopId
     *
     * @param shopid the value for shop.shopId
     *
     * @mbg.generated Tue May 14 10:43:09 CST 2019
     */
    public void setShopid(Integer shopid) {
        this.shopid = shopid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop.shopPriority
     *
     * @return the value of shop.shopPriority
     *
     * @mbg.generated Tue May 14 10:43:09 CST 2019
     */
    public Integer getShoppriority() {
        return shoppriority;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop.shopPriority
     *
     * @param shoppriority the value for shop.shopPriority
     *
     * @mbg.generated Tue May 14 10:43:09 CST 2019
     */
    public void setShoppriority(Integer shoppriority) {
        this.shoppriority = shoppriority;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop.shopImg
     *
     * @return the value of shop.shopImg
     *
     * @mbg.generated Tue May 14 10:43:09 CST 2019
     */
    public String getShopimg() {
        return shopimg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop.shopImg
     *
     * @param shopimg the value for shop.shopImg
     *
     * @mbg.generated Tue May 14 10:43:09 CST 2019
     */
    public void setShopimg(String shopimg) {
        this.shopimg = shopimg == null ? null : shopimg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop.shopName
     *
     * @return the value of shop.shopName
     *
     * @mbg.generated Tue May 14 10:43:09 CST 2019
     */
    public String getShopname() {
        return shopname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop.shopName
     *
     * @param shopname the value for shop.shopName
     *
     * @mbg.generated Tue May 14 10:43:09 CST 2019
     */
    public void setShopname(String shopname) {
        this.shopname = shopname == null ? null : shopname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop.shopDesc
     *
     * @return the value of shop.shopDesc
     *
     * @mbg.generated Tue May 14 10:43:09 CST 2019
     */
    public String getShopdesc() {
        return shopdesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop.shopDesc
     *
     * @param shopdesc the value for shop.shopDesc
     *
     * @mbg.generated Tue May 14 10:43:09 CST 2019
     */
    public void setShopdesc(String shopdesc) {
        this.shopdesc = shopdesc == null ? null : shopdesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop.shopPhoneNumber
     *
     * @return the value of shop.shopPhoneNumber
     *
     * @mbg.generated Tue May 14 10:43:09 CST 2019
     */
    public String getShopphonenumber() {
        return shopphonenumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop.shopPhoneNumber
     *
     * @param shopphonenumber the value for shop.shopPhoneNumber
     *
     * @mbg.generated Tue May 14 10:43:09 CST 2019
     */
    public void setShopphonenumber(String shopphonenumber) {
        this.shopphonenumber = shopphonenumber == null ? null : shopphonenumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop.shopPlace
     *
     * @return the value of shop.shopPlace
     *
     * @mbg.generated Tue May 14 10:43:09 CST 2019
     */
    public String getShopplace() {
        return shopplace;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop.shopPlace
     *
     * @param shopplace the value for shop.shopPlace
     *
     * @mbg.generated Tue May 14 10:43:09 CST 2019
     */
    public void setShopplace(String shopplace) {
        this.shopplace = shopplace == null ? null : shopplace.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop.placeId
     *
     * @return the value of shop.placeId
     *
     * @mbg.generated Tue May 14 10:43:09 CST 2019
     */
    public Integer getPlaceid() {
        return placeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop.placeId
     *
     * @param placeid the value for shop.placeId
     *
     * @mbg.generated Tue May 14 10:43:09 CST 2019
     */
    public void setPlaceid(Integer placeid) {
        this.placeid = placeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop.shopCategoryId
     *
     * @return the value of shop.shopCategoryId
     *
     * @mbg.generated Tue May 14 10:43:09 CST 2019
     */
    public Integer getShopcategoryid() {
        return shopcategoryid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop.shopCategoryId
     *
     * @param shopcategoryid the value for shop.shopCategoryId
     *
     * @mbg.generated Tue May 14 10:43:09 CST 2019
     */
    public void setShopcategoryid(Integer shopcategoryid) {
        this.shopcategoryid = shopcategoryid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop.userId
     *
     * @return the value of shop.userId
     *
     * @mbg.generated Tue May 14 10:43:09 CST 2019
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop.userId
     *
     * @param userid the value for shop.userId
     *
     * @mbg.generated Tue May 14 10:43:09 CST 2019
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop.shopStatus
     *
     * @return the value of shop.shopStatus
     *
     * @mbg.generated Tue May 14 10:43:09 CST 2019
     */
    public Integer getShopstatus() {
        return shopstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop.shopStatus
     *
     * @param shopstatus the value for shop.shopStatus
     *
     * @mbg.generated Tue May 14 10:43:09 CST 2019
     */
    public void setShopstatus(Integer shopstatus) {
        this.shopstatus = shopstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop.shopCreateTime
     *
     * @return the value of shop.shopCreateTime
     *
     * @mbg.generated Tue May 14 10:43:09 CST 2019
     */
    public Date getShopcreatetime() {
        return shopcreatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop.shopCreateTime
     *
     * @param shopcreatetime the value for shop.shopCreateTime
     *
     * @mbg.generated Tue May 14 10:43:09 CST 2019
     */
    public void setShopcreatetime(Date shopcreatetime) {
        this.shopcreatetime = shopcreatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop.shopUpdateTime
     *
     * @return the value of shop.shopUpdateTime
     *
     * @mbg.generated Tue May 14 10:43:09 CST 2019
     */
    public Date getShopupdatetime() {
        return shopupdatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop.shopUpdateTime
     *
     * @param shopupdatetime the value for shop.shopUpdateTime
     *
     * @mbg.generated Tue May 14 10:43:09 CST 2019
     */
    public void setShopupdatetime(Date shopupdatetime) {
        this.shopupdatetime = shopupdatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop.shopAdvice
     *
     * @return the value of shop.shopAdvice
     *
     * @mbg.generated Tue May 14 10:43:09 CST 2019
     */
    public String getShopadvice() {
        return shopadvice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop.shopAdvice
     *
     * @param shopadvice the value for shop.shopAdvice
     *
     * @mbg.generated Tue May 14 10:43:09 CST 2019
     */
    public void setShopadvice(String shopadvice) {
        this.shopadvice = shopadvice == null ? null : shopadvice.trim();
    }

    @Override
    public String toString() {
        return "Shop{" +
                "shopid=" + shopid +
                ", shoppriority=" + shoppriority +
                ", shopimg='" + shopimg + '\'' +
                ", shopname='" + shopname + '\'' +
                ", shopdesc='" + shopdesc + '\'' +
                ", shopphonenumber='" + shopphonenumber + '\'' +
                ", shopplace='" + shopplace + '\'' +
                ", placeid=" + placeid +
                ", shopcategoryid=" + shopcategoryid +
                ", userid=" + userid +
                ", shopstatus=" + shopstatus +
                ", shopcreatetime=" + shopcreatetime +
                ", shopupdatetime=" + shopupdatetime +
                ", shopadvice='" + shopadvice + '\'' +
                '}';
    }
}