package club.bagedate.o2o.entity;

import java.util.Date;

public class User {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.userId
     *
     * @mbg.generated Tue May 14 10:43:09 CST 2019
     */
    private Integer userid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.name
     *
     * @mbg.generated Tue May 14 10:43:09 CST 2019
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.userImg
     *
     * @mbg.generated Tue May 14 10:43:09 CST 2019
     */
    private String userimg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.userEmail
     *
     * @mbg.generated Tue May 14 10:43:09 CST 2019
     */
    private String useremail;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.userGender
     *
     * @mbg.generated Tue May 14 10:43:09 CST 2019
     */
    private String usergender;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.userStatus
     *
     * @mbg.generated Tue May 14 10:43:09 CST 2019
     */
    private Integer userstatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.userType
     *
     * @mbg.generated Tue May 14 10:43:09 CST 2019
     */
    private Integer usertype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.userCreateTime
     *
     * @mbg.generated Tue May 14 10:43:09 CST 2019
     */
    private Date usercreatetime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.userUpdateTime
     *
     * @mbg.generated Tue May 14 10:43:09 CST 2019
     */
    private Date userupdatetime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.userId
     *
     * @return the value of user.userId
     *
     * @mbg.generated Tue May 14 10:43:09 CST 2019
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.userId
     *
     * @param userid the value for user.userId
     *
     * @mbg.generated Tue May 14 10:43:09 CST 2019
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.name
     *
     * @return the value of user.name
     *
     * @mbg.generated Tue May 14 10:43:09 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.name
     *
     * @param name the value for user.name
     *
     * @mbg.generated Tue May 14 10:43:09 CST 2019
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.userImg
     *
     * @return the value of user.userImg
     *
     * @mbg.generated Tue May 14 10:43:09 CST 2019
     */
    public String getUserimg() {
        return userimg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.userImg
     *
     * @param userimg the value for user.userImg
     *
     * @mbg.generated Tue May 14 10:43:09 CST 2019
     */
    public void setUserimg(String userimg) {
        this.userimg = userimg == null ? null : userimg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.userEmail
     *
     * @return the value of user.userEmail
     *
     * @mbg.generated Tue May 14 10:43:09 CST 2019
     */
    public String getUseremail() {
        return useremail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.userEmail
     *
     * @param useremail the value for user.userEmail
     *
     * @mbg.generated Tue May 14 10:43:09 CST 2019
     */
    public void setUseremail(String useremail) {
        this.useremail = useremail == null ? null : useremail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.userGender
     *
     * @return the value of user.userGender
     *
     * @mbg.generated Tue May 14 10:43:09 CST 2019
     */
    public String getUsergender() {
        return usergender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.userGender
     *
     * @param usergender the value for user.userGender
     *
     * @mbg.generated Tue May 14 10:43:09 CST 2019
     */
    public void setUsergender(String usergender) {
        this.usergender = usergender == null ? null : usergender.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.userStatus
     *
     * @return the value of user.userStatus
     *
     * @mbg.generated Tue May 14 10:43:09 CST 2019
     */
    public Integer getUserstatus() {
        return userstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.userStatus
     *
     * @param userstatus the value for user.userStatus
     *
     * @mbg.generated Tue May 14 10:43:09 CST 2019
     */
    public void setUserstatus(Integer userstatus) {
        this.userstatus = userstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.userType
     *
     * @return the value of user.userType
     *
     * @mbg.generated Tue May 14 10:43:09 CST 2019
     */
    public Integer getUsertype() {
        return usertype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.userType
     *
     * @param usertype the value for user.userType
     *
     * @mbg.generated Tue May 14 10:43:09 CST 2019
     */
    public void setUsertype(Integer usertype) {
        this.usertype = usertype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.userCreateTime
     *
     * @return the value of user.userCreateTime
     *
     * @mbg.generated Tue May 14 10:43:09 CST 2019
     */
    public Date getUsercreatetime() {
        return usercreatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.userCreateTime
     *
     * @param usercreatetime the value for user.userCreateTime
     *
     * @mbg.generated Tue May 14 10:43:09 CST 2019
     */
    public void setUsercreatetime(Date usercreatetime) {
        this.usercreatetime = usercreatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.userUpdateTime
     *
     * @return the value of user.userUpdateTime
     *
     * @mbg.generated Tue May 14 10:43:09 CST 2019
     */
    public Date getUserupdatetime() {
        return userupdatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.userUpdateTime
     *
     * @param userupdatetime the value for user.userUpdateTime
     *
     * @mbg.generated Tue May 14 10:43:09 CST 2019
     */
    public void setUserupdatetime(Date userupdatetime) {
        this.userupdatetime = userupdatetime;
    }
}