package club.bagedate.o2o.entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class WeChetAuthExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table wechetauth
     *
     * @mbg.generated Tue May 14 10:43:09 CST 2019
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table wechetauth
     *
     * @mbg.generated Tue May 14 10:43:09 CST 2019
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table wechetauth
     *
     * @mbg.generated Tue May 14 10:43:09 CST 2019
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wechetauth
     *
     * @mbg.generated Tue May 14 10:43:09 CST 2019
     */
    public WeChetAuthExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wechetauth
     *
     * @mbg.generated Tue May 14 10:43:09 CST 2019
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wechetauth
     *
     * @mbg.generated Tue May 14 10:43:09 CST 2019
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wechetauth
     *
     * @mbg.generated Tue May 14 10:43:09 CST 2019
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wechetauth
     *
     * @mbg.generated Tue May 14 10:43:09 CST 2019
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wechetauth
     *
     * @mbg.generated Tue May 14 10:43:09 CST 2019
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wechetauth
     *
     * @mbg.generated Tue May 14 10:43:09 CST 2019
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wechetauth
     *
     * @mbg.generated Tue May 14 10:43:09 CST 2019
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wechetauth
     *
     * @mbg.generated Tue May 14 10:43:09 CST 2019
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wechetauth
     *
     * @mbg.generated Tue May 14 10:43:09 CST 2019
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wechetauth
     *
     * @mbg.generated Tue May 14 10:43:09 CST 2019
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table wechetauth
     *
     * @mbg.generated Tue May 14 10:43:09 CST 2019
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andWeidIsNull() {
            addCriterion("weId is null");
            return (Criteria) this;
        }

        public Criteria andWeidIsNotNull() {
            addCriterion("weId is not null");
            return (Criteria) this;
        }

        public Criteria andWeidEqualTo(Integer value) {
            addCriterion("weId =", value, "weid");
            return (Criteria) this;
        }

        public Criteria andWeidNotEqualTo(Integer value) {
            addCriterion("weId <>", value, "weid");
            return (Criteria) this;
        }

        public Criteria andWeidGreaterThan(Integer value) {
            addCriterion("weId >", value, "weid");
            return (Criteria) this;
        }

        public Criteria andWeidGreaterThanOrEqualTo(Integer value) {
            addCriterion("weId >=", value, "weid");
            return (Criteria) this;
        }

        public Criteria andWeidLessThan(Integer value) {
            addCriterion("weId <", value, "weid");
            return (Criteria) this;
        }

        public Criteria andWeidLessThanOrEqualTo(Integer value) {
            addCriterion("weId <=", value, "weid");
            return (Criteria) this;
        }

        public Criteria andWeidIn(List<Integer> values) {
            addCriterion("weId in", values, "weid");
            return (Criteria) this;
        }

        public Criteria andWeidNotIn(List<Integer> values) {
            addCriterion("weId not in", values, "weid");
            return (Criteria) this;
        }

        public Criteria andWeidBetween(Integer value1, Integer value2) {
            addCriterion("weId between", value1, value2, "weid");
            return (Criteria) this;
        }

        public Criteria andWeidNotBetween(Integer value1, Integer value2) {
            addCriterion("weId not between", value1, value2, "weid");
            return (Criteria) this;
        }

        public Criteria andUseridIsNull() {
            addCriterion("userId is null");
            return (Criteria) this;
        }

        public Criteria andUseridIsNotNull() {
            addCriterion("userId is not null");
            return (Criteria) this;
        }

        public Criteria andUseridEqualTo(Integer value) {
            addCriterion("userId =", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridNotEqualTo(Integer value) {
            addCriterion("userId <>", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridGreaterThan(Integer value) {
            addCriterion("userId >", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridGreaterThanOrEqualTo(Integer value) {
            addCriterion("userId >=", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridLessThan(Integer value) {
            addCriterion("userId <", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridLessThanOrEqualTo(Integer value) {
            addCriterion("userId <=", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridIn(List<Integer> values) {
            addCriterion("userId in", values, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridNotIn(List<Integer> values) {
            addCriterion("userId not in", values, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridBetween(Integer value1, Integer value2) {
            addCriterion("userId between", value1, value2, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridNotBetween(Integer value1, Integer value2) {
            addCriterion("userId not between", value1, value2, "userid");
            return (Criteria) this;
        }

        public Criteria andWeopenidIsNull() {
            addCriterion("weOpenId is null");
            return (Criteria) this;
        }

        public Criteria andWeopenidIsNotNull() {
            addCriterion("weOpenId is not null");
            return (Criteria) this;
        }

        public Criteria andWeopenidEqualTo(String value) {
            addCriterion("weOpenId =", value, "weopenid");
            return (Criteria) this;
        }

        public Criteria andWeopenidNotEqualTo(String value) {
            addCriterion("weOpenId <>", value, "weopenid");
            return (Criteria) this;
        }

        public Criteria andWeopenidGreaterThan(String value) {
            addCriterion("weOpenId >", value, "weopenid");
            return (Criteria) this;
        }

        public Criteria andWeopenidGreaterThanOrEqualTo(String value) {
            addCriterion("weOpenId >=", value, "weopenid");
            return (Criteria) this;
        }

        public Criteria andWeopenidLessThan(String value) {
            addCriterion("weOpenId <", value, "weopenid");
            return (Criteria) this;
        }

        public Criteria andWeopenidLessThanOrEqualTo(String value) {
            addCriterion("weOpenId <=", value, "weopenid");
            return (Criteria) this;
        }

        public Criteria andWeopenidLike(String value) {
            addCriterion("weOpenId like", value, "weopenid");
            return (Criteria) this;
        }

        public Criteria andWeopenidNotLike(String value) {
            addCriterion("weOpenId not like", value, "weopenid");
            return (Criteria) this;
        }

        public Criteria andWeopenidIn(List<String> values) {
            addCriterion("weOpenId in", values, "weopenid");
            return (Criteria) this;
        }

        public Criteria andWeopenidNotIn(List<String> values) {
            addCriterion("weOpenId not in", values, "weopenid");
            return (Criteria) this;
        }

        public Criteria andWeopenidBetween(String value1, String value2) {
            addCriterion("weOpenId between", value1, value2, "weopenid");
            return (Criteria) this;
        }

        public Criteria andWeopenidNotBetween(String value1, String value2) {
            addCriterion("weOpenId not between", value1, value2, "weopenid");
            return (Criteria) this;
        }

        public Criteria andWeidcreatetimeIsNull() {
            addCriterion("weIdCreateTime is null");
            return (Criteria) this;
        }

        public Criteria andWeidcreatetimeIsNotNull() {
            addCriterion("weIdCreateTime is not null");
            return (Criteria) this;
        }

        public Criteria andWeidcreatetimeEqualTo(Date value) {
            addCriterion("weIdCreateTime =", value, "weidcreatetime");
            return (Criteria) this;
        }

        public Criteria andWeidcreatetimeNotEqualTo(Date value) {
            addCriterion("weIdCreateTime <>", value, "weidcreatetime");
            return (Criteria) this;
        }

        public Criteria andWeidcreatetimeGreaterThan(Date value) {
            addCriterion("weIdCreateTime >", value, "weidcreatetime");
            return (Criteria) this;
        }

        public Criteria andWeidcreatetimeGreaterThanOrEqualTo(Date value) {
            addCriterion("weIdCreateTime >=", value, "weidcreatetime");
            return (Criteria) this;
        }

        public Criteria andWeidcreatetimeLessThan(Date value) {
            addCriterion("weIdCreateTime <", value, "weidcreatetime");
            return (Criteria) this;
        }

        public Criteria andWeidcreatetimeLessThanOrEqualTo(Date value) {
            addCriterion("weIdCreateTime <=", value, "weidcreatetime");
            return (Criteria) this;
        }

        public Criteria andWeidcreatetimeIn(List<Date> values) {
            addCriterion("weIdCreateTime in", values, "weidcreatetime");
            return (Criteria) this;
        }

        public Criteria andWeidcreatetimeNotIn(List<Date> values) {
            addCriterion("weIdCreateTime not in", values, "weidcreatetime");
            return (Criteria) this;
        }

        public Criteria andWeidcreatetimeBetween(Date value1, Date value2) {
            addCriterion("weIdCreateTime between", value1, value2, "weidcreatetime");
            return (Criteria) this;
        }

        public Criteria andWeidcreatetimeNotBetween(Date value1, Date value2) {
            addCriterion("weIdCreateTime not between", value1, value2, "weidcreatetime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table wechetauth
     *
     * @mbg.generated do_not_delete_during_merge Tue May 14 10:43:09 CST 2019
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table wechetauth
     *
     * @mbg.generated Tue May 14 10:43:09 CST 2019
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}