package club.bagedate.o2o.entity;

import java.util.Date;

public class WeChetAuth {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wechetauth.weId
     *
     * @mbg.generated Tue May 14 10:43:09 CST 2019
     */
    private Integer weid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wechetauth.userId
     *
     * @mbg.generated Tue May 14 10:43:09 CST 2019
     */
    private Integer userid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wechetauth.weOpenId
     *
     * @mbg.generated Tue May 14 10:43:09 CST 2019
     */
    private String weopenid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wechetauth.weIdCreateTime
     *
     * @mbg.generated Tue May 14 10:43:09 CST 2019
     */
    private Date weidcreatetime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wechetauth.weId
     *
     * @return the value of wechetauth.weId
     *
     * @mbg.generated Tue May 14 10:43:09 CST 2019
     */
    public Integer getWeid() {
        return weid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wechetauth.weId
     *
     * @param weid the value for wechetauth.weId
     *
     * @mbg.generated Tue May 14 10:43:09 CST 2019
     */
    public void setWeid(Integer weid) {
        this.weid = weid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wechetauth.userId
     *
     * @return the value of wechetauth.userId
     *
     * @mbg.generated Tue May 14 10:43:09 CST 2019
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wechetauth.userId
     *
     * @param userid the value for wechetauth.userId
     *
     * @mbg.generated Tue May 14 10:43:09 CST 2019
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wechetauth.weOpenId
     *
     * @return the value of wechetauth.weOpenId
     *
     * @mbg.generated Tue May 14 10:43:09 CST 2019
     */
    public String getWeopenid() {
        return weopenid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wechetauth.weOpenId
     *
     * @param weopenid the value for wechetauth.weOpenId
     *
     * @mbg.generated Tue May 14 10:43:09 CST 2019
     */
    public void setWeopenid(String weopenid) {
        this.weopenid = weopenid == null ? null : weopenid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wechetauth.weIdCreateTime
     *
     * @return the value of wechetauth.weIdCreateTime
     *
     * @mbg.generated Tue May 14 10:43:09 CST 2019
     */
    public Date getWeidcreatetime() {
        return weidcreatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wechetauth.weIdCreateTime
     *
     * @param weidcreatetime the value for wechetauth.weIdCreateTime
     *
     * @mbg.generated Tue May 14 10:43:09 CST 2019
     */
    public void setWeidcreatetime(Date weidcreatetime) {
        this.weidcreatetime = weidcreatetime;
    }
}