package club.bagedate.o2o.mapper;

import club.bagedate.o2o.entity.HeadLine;
import club.bagedate.o2o.entity.HeadLineExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface HeadLineMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table headline
     *
     * @mbg.generated Tue May 14 10:48:08 CST 2019
     */
    long countByExample(HeadLineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table headline
     *
     * @mbg.generated Tue May 14 10:48:08 CST 2019
     */
    int deleteByExample(HeadLineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table headline
     *
     * @mbg.generated Tue May 14 10:48:08 CST 2019
     */
    int deleteByPrimaryKey(Integer lineid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table headline
     *
     * @mbg.generated Tue May 14 10:48:08 CST 2019
     */
    int insert(HeadLine record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table headline
     *
     * @mbg.generated Tue May 14 10:48:08 CST 2019
     */
    int insertSelective(HeadLine record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table headline
     *
     * @mbg.generated Tue May 14 10:48:08 CST 2019
     */
    List<HeadLine> selectByExample(HeadLineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table headline
     *
     * @mbg.generated Tue May 14 10:48:08 CST 2019
     */
    HeadLine selectByPrimaryKey(Integer lineid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table headline
     *
     * @mbg.generated Tue May 14 10:48:08 CST 2019
     */
    int updateByExampleSelective(@Param("record") HeadLine record, @Param("example") HeadLineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table headline
     *
     * @mbg.generated Tue May 14 10:48:08 CST 2019
     */
    int updateByExample(@Param("record") HeadLine record, @Param("example") HeadLineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table headline
     *
     * @mbg.generated Tue May 14 10:48:08 CST 2019
     */
    int updateByPrimaryKeySelective(HeadLine record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table headline
     *
     * @mbg.generated Tue May 14 10:48:08 CST 2019
     */
    int updateByPrimaryKey(HeadLine record);
}