package club.bagedate.o2o.mapper;

import club.bagedate.o2o.entity.LocalAuth;
import club.bagedate.o2o.entity.LocalAuthExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface LocalAuthMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table localauth
     *
     * @mbg.generated Tue May 14 10:48:08 CST 2019
     */
    long countByExample(LocalAuthExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table localauth
     *
     * @mbg.generated Tue May 14 10:48:08 CST 2019
     */
    int deleteByExample(LocalAuthExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table localauth
     *
     * @mbg.generated Tue May 14 10:48:08 CST 2019
     */
    int deleteByPrimaryKey(Integer localid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table localauth
     *
     * @mbg.generated Tue May 14 10:48:08 CST 2019
     */
    int insert(LocalAuth record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table localauth
     *
     * @mbg.generated Tue May 14 10:48:08 CST 2019
     */
    int insertSelective(LocalAuth record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table localauth
     *
     * @mbg.generated Tue May 14 10:48:08 CST 2019
     */
    List<LocalAuth> selectByExample(LocalAuthExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table localauth
     *
     * @mbg.generated Tue May 14 10:48:08 CST 2019
     */
    LocalAuth selectByPrimaryKey(Integer localid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table localauth
     *
     * @mbg.generated Tue May 14 10:48:08 CST 2019
     */
    int updateByExampleSelective(@Param("record") LocalAuth record, @Param("example") LocalAuthExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table localauth
     *
     * @mbg.generated Tue May 14 10:48:08 CST 2019
     */
    int updateByExample(@Param("record") LocalAuth record, @Param("example") LocalAuthExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table localauth
     *
     * @mbg.generated Tue May 14 10:48:08 CST 2019
     */
    int updateByPrimaryKeySelective(LocalAuth record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table localauth
     *
     * @mbg.generated Tue May 14 10:48:08 CST 2019
     */
    int updateByPrimaryKey(LocalAuth record);
}