package club.bagedate.o2o.mapper;

import club.bagedate.o2o.entity.Place;
import club.bagedate.o2o.entity.PlaceExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PlaceMapper {
    List<Place> queryPlace();
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table place
     *
     * @mbg.generated Tue May 14 10:48:08 CST 2019
     */
    long countByExample(PlaceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table place
     *
     * @mbg.generated Tue May 14 10:48:08 CST 2019
     */
    int deleteByExample(PlaceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table place
     *
     * @mbg.generated Tue May 14 10:48:08 CST 2019
     */
    int deleteByPrimaryKey(Integer placeid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table place
     *
     * @mbg.generated Tue May 14 10:48:08 CST 2019
     */
    int insert(Place record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table place
     *
     * @mbg.generated Tue May 14 10:48:08 CST 2019
     */
    int insertSelective(Place record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table place
     *
     * @mbg.generated Tue May 14 10:48:08 CST 2019
     */
    List<Place> selectByExample(PlaceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table place
     *
     * @mbg.generated Tue May 14 10:48:08 CST 2019
     */
    Place selectByPrimaryKey(Integer placeid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table place
     *
     * @mbg.generated Tue May 14 10:48:08 CST 2019
     */
    int updateByExampleSelective(@Param("record") Place record, @Param("example") PlaceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table place
     *
     * @mbg.generated Tue May 14 10:48:08 CST 2019
     */
    int updateByExample(@Param("record") Place record, @Param("example") PlaceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table place
     *
     * @mbg.generated Tue May 14 10:48:08 CST 2019
     */
    int updateByPrimaryKeySelective(Place record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table place
     *
     * @mbg.generated Tue May 14 10:48:08 CST 2019
     */
    int updateByPrimaryKey(Place record);
}