package club.bagedate.o2o.mapper;

import club.bagedate.o2o.entity.ProductImg;
import club.bagedate.o2o.entity.ProductImgExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ProductImgMapper {
    /**
     * 批量添加
     * @param productImgList
     * @return
     */
    int batchInsertProductImg(List<ProductImg> productImgList);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table productimg
     *
     * @mbg.generated Tue May 14 10:48:08 CST 2019
     */
    long countByExample(ProductImgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table productimg
     *
     * @mbg.generated Tue May 14 10:48:08 CST 2019
     */
    int deleteByExample(ProductImgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table productimg
     *
     * @mbg.generated Tue May 14 10:48:08 CST 2019
     */
    int deleteByPrimaryKey(Integer productimgid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table productimg
     *
     * @mbg.generated Tue May 14 10:48:08 CST 2019
     */
    int insert(ProductImg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table productimg
     *
     * @mbg.generated Tue May 14 10:48:08 CST 2019
     */
    int insertSelective(ProductImg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table productimg
     *
     * @mbg.generated Tue May 14 10:48:08 CST 2019
     */
    List<ProductImg> selectByExample(ProductImgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table productimg
     *
     * @mbg.generated Tue May 14 10:48:08 CST 2019
     */
    ProductImg selectByPrimaryKey(Integer productimgid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table productimg
     *
     * @mbg.generated Tue May 14 10:48:08 CST 2019
     */
    int updateByExampleSelective(@Param("record") ProductImg record, @Param("example") ProductImgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table productimg
     *
     * @mbg.generated Tue May 14 10:48:08 CST 2019
     */
    int updateByExample(@Param("record") ProductImg record, @Param("example") ProductImgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table productimg
     *
     * @mbg.generated Tue May 14 10:48:08 CST 2019
     */
    int updateByPrimaryKeySelective(ProductImg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table productimg
     *
     * @mbg.generated Tue May 14 10:48:08 CST 2019
     */
    int updateByPrimaryKey(ProductImg record);
}