package club.bagedate.o2o.mapper;

import club.bagedate.o2o.entity.ProductCategory;
import club.bagedate.o2o.entity.ProductCategoryExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ProductCategoryMapper {
    /**
     * 批量新增商品类别
     * @param productCategoryList
     * @return 影响的行数
     */
    int batchInsertProductCategory(List<ProductCategory> productCategoryList);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table productcategory
     *
     * @mbg.generated Tue May 14 10:48:08 CST 2019
     */
    long countByExample(ProductCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table productcategory
     *
     * @mbg.generated Tue May 14 10:48:08 CST 2019
     */
    int deleteByExample(ProductCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table productcategory
     *
     * @mbg.generated Tue May 14 10:48:08 CST 2019
     */
    int deleteByPrimaryKey(Integer productcategoryid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table productcategory
     *
     * @mbg.generated Tue May 14 10:48:08 CST 2019
     */
    int insert(ProductCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table productcategory
     *
     * @mbg.generated Tue May 14 10:48:08 CST 2019
     */
    int insertSelective(ProductCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table productcategory
     *
     * @mbg.generated Tue May 14 10:48:08 CST 2019
     */
    List<ProductCategory> selectByExample(ProductCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table productcategory
     *
     * @mbg.generated Tue May 14 10:48:08 CST 2019
     */
    ProductCategory selectByPrimaryKey(Integer productcategoryid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table productcategory
     *
     * @mbg.generated Tue May 14 10:48:08 CST 2019
     */
    int updateByExampleSelective(@Param("record") ProductCategory record, @Param("example") ProductCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table productcategory
     *
     * @mbg.generated Tue May 14 10:48:08 CST 2019
     */
    int updateByExample(@Param("record") ProductCategory record, @Param("example") ProductCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table productcategory
     *
     * @mbg.generated Tue May 14 10:48:08 CST 2019
     */
    int updateByPrimaryKeySelective(ProductCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table productcategory
     *
     * @mbg.generated Tue May 14 10:48:08 CST 2019
     */
    int updateByPrimaryKey(ProductCategory record);
}