package club.bagedate.o2o.mapper;

import club.bagedate.o2o.entity.WeChetAuth;
import club.bagedate.o2o.entity.WeChetAuthExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface WeChetAuthMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wechetauth
     *
     * @mbg.generated Tue May 14 10:48:08 CST 2019
     */
    long countByExample(WeChetAuthExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wechetauth
     *
     * @mbg.generated Tue May 14 10:48:08 CST 2019
     */
    int deleteByExample(WeChetAuthExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wechetauth
     *
     * @mbg.generated Tue May 14 10:48:08 CST 2019
     */
    int deleteByPrimaryKey(Integer weid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wechetauth
     *
     * @mbg.generated Tue May 14 10:48:08 CST 2019
     */
    int insert(WeChetAuth record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wechetauth
     *
     * @mbg.generated Tue May 14 10:48:08 CST 2019
     */
    int insertSelective(WeChetAuth record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wechetauth
     *
     * @mbg.generated Tue May 14 10:48:08 CST 2019
     */
    List<WeChetAuth> selectByExample(WeChetAuthExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wechetauth
     *
     * @mbg.generated Tue May 14 10:48:08 CST 2019
     */
    WeChetAuth selectByPrimaryKey(Integer weid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wechetauth
     *
     * @mbg.generated Tue May 14 10:48:08 CST 2019
     */
    int updateByExampleSelective(@Param("record") WeChetAuth record, @Param("example") WeChetAuthExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wechetauth
     *
     * @mbg.generated Tue May 14 10:48:08 CST 2019
     */
    int updateByExample(@Param("record") WeChetAuth record, @Param("example") WeChetAuthExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wechetauth
     *
     * @mbg.generated Tue May 14 10:48:08 CST 2019
     */
    int updateByPrimaryKeySelective(WeChetAuth record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wechetauth
     *
     * @mbg.generated Tue May 14 10:48:08 CST 2019
     */
    int updateByPrimaryKey(WeChetAuth record);
}